#!/usr/bin/env bash
# SedSAT3 repository hygiene cleanup
# Run this from the root of your SedSat3 working copy, on a clean main branch.
set -e

echo "Removing generated Doxygen output (regenerated by docs.yml -> gh-pages)..."
git rm -r --quiet docs/html docs/latex
git rm --quiet docs/doxygen_warnings.log docs/sedsat3.tag

echo "Removing stray / backup / generated cruft..."
git rm --quiet "et --hard 009aef0"
git rm --quiet GIFMod.aip "CMB_Source.back.aip"
git rm --quiet "SedSat3 - Backup (1).vcxproj.user" "SedSat3 - Backup.vcxproj.user" "SedSat3.vcxproj.user"
git rm --quiet moc_predefs.h

echo "Updating .gitignore..."
cat >> .gitignore << 'IGNORE'

# Generated Doxygen output (regenerated by docs.yml GitHub Action, served from gh-pages)
docs/html/
docs/latex/
docs/sedsat3.tag
docs/doxygen_warnings.log

# Qt moc-generated predefs
moc_predefs.h

# Visual Studio per-user settings (exact match; complements existing *vcproj.*.*.user)
*.vcxproj.user

# Manual backup files
*.back.aip
* - Backup*.vcxproj.user
IGNORE

git add .gitignore

echo
echo "Staged. Review with:  git status --short | head"
echo "Then:  git commit -m 'Repo hygiene: untrack generated docs and cruft, extend .gitignore'"
echo "       git push"
