SedSat3: GeneralChart Class Reference
GeneralChart Class Reference
#include </home/runner/work/SedSat3/SedSat3/generalchart.h>
Public Member Functions
GeneralChart (QWidget *parent=nullptr)
~GeneralChart ()
bool Plot (ResultItem *res)
bool PlotVector (CMBVector *profile, const QString &title)
bool PlotVectorSet (CMBVectorSet *profile, const QString &title)
bool PlotVectorSetSet (CMBVectorSetSet *profile, const QString &title)
bool PlotMatrix (CMBMatrix *matrix, const QString &title)
bool PlotProfileSet (Elemental_Profile_Set *elementalprofileset, const QString &title)
bool PlotContribution (Contribution *contributions, const QString &title)
bool PlotPredictedConcentration (Elemental_Profile *elemental_profile, const QString &title)
bool PlotRegressionSet (MultipleLinearRegressionSet *regressionset, const QString &title)
bool PlotTimeSeriesSet (CMBTimeSeriesSet *regressionset, const QString &title, const QString &x_axis_title="", const QString &y_axis_title="")
bool PlotTimeSeriesSet_M (CMBTimeSeriesSet *timeseriesset, const QString &title, const QString &x_axis_title="", const QString &y_axis_title="")
bool PlotTimeSeriesSet_A (CMBTimeSeriesSet *timeseriesset, const QString &title, const QString &x_axis_title="", const QString &y_axis_title="")
bool PlotTimeSeriesSet_Stacked (CMBTimeSeriesSet *timeseriesset, const QString &title, const QString &x_axis_title, const QString &y_axis_title="")
bool PlotRangeSet (RangeSet *rangeset, const QString &title, const QString &x_axis_title, const QString &y_axis_title)
bool InitializeMCMCSamples (CMBTimeSeriesSet *mcmcsamples, const QString &title)
bool InitializeDistributions (CMBTimeSeriesSet *distributions, const QString &title)
bool PlotMCMCSamples (TimeSeries< double > *mlr, const QString &variable)
bool PlotDistribution (TimeSeries< double > *mlr, const QString &variable)
bool PlotScatter (CMBMatrix *matrix)
bool PlotScatter (CMBVectorSet *vectorset)
bool PlotScatter (CMBVectorSet *vectorset1, CMBVectorSet *vectorset2, const QString &xaxis_title, const QString &yaxistitle)
Private Member Functions
bool PlotRegression (MultipleLinearRegression *timeseriesset, const QString &independent_var)
void onIndependentChanged (int i_independent)
void onElementChanged (int i_constituent)
void onPairChanged (int pair_id)
void onDFAPairChanged (int pair_id)
void onMCMCVariableChanged (int)
void onDistributionsVariableChanged (int)
void on_Exporttopng ()
std::vector< QPointF > calculateRotatedEllipsePoints (double centerX, double centerY, double semiMajorAxis, double semiMinorAxis, double rotationAngle, double interval)
Private Attributes
Ui::GeneralChart * ui
Chart * chart
ChartView * chartView
QComboBox * element_combo
QComboBox * source1_combo
QComboBox * source2_combo
QComboBox * independent_combo
ResultItem * result_item =nullptr
Detailed Description
Definition at line 27 of file generalchart.h.
Constructor & Destructor Documentation
GeneralChart()
GeneralChart::GeneralChart (QWidget * parent = nullptr) explicit
Definition at line 7 of file generalchart.cpp.
References chart, chartView, on_Exporttopng(), and ui.
~GeneralChart()
GeneralChart::~GeneralChart ()
Definition at line 19 of file generalchart.cpp.
References ui.
Member Function Documentation
calculateRotatedEllipsePoints()
std::vector< QPointF > GeneralChart::calculateRotatedEllipsePoints (double centerX, double centerY, double semiMajorAxis, double semiMinorAxis, double rotationAngle, double interval) private
Definition at line 1461 of file generalchart.cpp.
References x, and y.
Referenced by PlotScatter().
InitializeDistributions()
bool GeneralChart::InitializeDistributions (CMBTimeSeriesSet * distributions, const QString & title)
Definition at line 540 of file generalchart.cpp.
References element_combo, onDistributionsVariableChanged(), and ui.
Referenced by Plot().
InitializeMCMCSamples()
bool GeneralChart::InitializeMCMCSamples (CMBTimeSeriesSet * mcmcsamples, const QString & title)
Definition at line 520 of file generalchart.cpp.
References element_combo, onMCMCVariableChanged(), and ui.
Referenced by Plot().
on_Exporttopng()
void GeneralChart::on_Exporttopng () private
Definition at line 1443 of file generalchart.cpp.
References chart, and chartView.
Referenced by GeneralChart().
onDFAPairChanged()
void GeneralChart::onDFAPairChanged (int pair_id) private
Definition at line 598 of file generalchart.cpp.
References chart, PlotScatter(), ResultItem::Result(), result_item, source1_combo, source2_combo, and vectorset.
Referenced by PlotVectorSetSet().
onDistributionsVariableChanged()
void GeneralChart::onDistributionsVariableChanged (int i) private
Definition at line 627 of file generalchart.cpp.
References element_combo, PlotDistribution(), ResultItem::Result(), and result_item.
Referenced by InitializeDistributions().
onElementChanged()
void GeneralChart::onElementChanged (int i_constituent) private
Definition at line 561 of file generalchart.cpp.
References element_combo, independent_combo, mlrset, PlotRegression(), ResultItem::Result(), and result_item.
Referenced by PlotRegressionSet().
onIndependentChanged()
void GeneralChart::onIndependentChanged (int i_independent) private
Definition at line 634 of file generalchart.cpp.
References element_combo, independent_combo, mlrset, PlotRegression(), ResultItem::Result(), and result_item.
Referenced by PlotRegressionSet().
onMCMCVariableChanged()
void GeneralChart::onMCMCVariableChanged (int i) private
Definition at line 620 of file generalchart.cpp.
References element_combo, PlotMCMCSamples(), ResultItem::Result(), and result_item.
Referenced by InitializeMCMCSamples().
onPairChanged()
void GeneralChart::onPairChanged (int pair_id) private
Definition at line 577 of file generalchart.cpp.
References chart, element_combo, PlotVector(), ResultItem::Result(), result_item, and vectorset.
Referenced by PlotVectorSet().
Plot()
bool GeneralChart::Plot (ResultItem * res)
Definition at line 24 of file generalchart.cpp.
References chartView, contribution, dfa_vectorsetset, distribution, distribution_with_observed, elemental_profile_set, InitializeDistributions(), InitializeMCMCSamples(), matrix, matrix1vs1, mcmc_samples, mlrset, ResultItem::Name(), PlotContribution(), PlotMatrix(), PlotPredictedConcentration(), PlotProfileSet(), PlotRangeSet(), PlotRegressionSet(), PlotScatter(), PlotTimeSeriesSet(), PlotTimeSeriesSet_M(), PlotTimeSeriesSet_Stacked(), PlotVector(), PlotVectorSet(), PlotVectorSetSet(), predicted_concentration, rangeset, rangeset_with_observed, ResultItem::Result(), result_item, stacked_bar_chart, timeseries_set, timeseries_set_first_symbol, ResultItem::Type(), vector, vectorset, vectorset_groups, ResultItem::XAxisTitle(), and ResultItem::YAxisTitle().
Referenced by ResultsWindow::on_result_graph_clicked().
PlotContribution()
bool GeneralChart::PlotContribution (Contribution * contributions, const QString & title)
Definition at line 404 of file generalchart.cpp.
References chart, and chartView.
Referenced by Plot().
PlotDistribution()
bool GeneralChart::PlotDistribution (TimeSeries< double > * mlr, const QString & variable)
Definition at line 1057 of file generalchart.cpp.
References chart, distribution_with_observed, CMBTimeSeriesSet::ObservedValue(), ResultItem::Result(), result_item, samples, and ResultItem::Type().
Referenced by onDistributionsVariableChanged().
PlotMatrix()
bool GeneralChart::PlotMatrix (CMBMatrix * matrix, const QString & title)
Definition at line 266 of file generalchart.cpp.
References ResultItem::AbsValue(), chart, counter, log, matrix, result_item, roundDown(), and ResultItem::YAxisMode().
Referenced by Plot().
PlotMCMCSamples()
bool GeneralChart::PlotMCMCSamples (TimeSeries< double > * mlr, const QString & variable)
Definition at line 992 of file generalchart.cpp.
References chart, and samples.
Referenced by onMCMCVariableChanged().
PlotPredictedConcentration()
bool GeneralChart::PlotPredictedConcentration (Elemental_Profile * elemental_profile, const QString & title)
Definition at line 434 of file generalchart.cpp.
References chart, counter, Elemental_Profile::GetElementNames(), Elemental_Profile::GetMaximum(), Elemental_Profile::GetMinimum(), high, log, low, result_item, roundDown(), ResultItem::XAxisTitle(), ResultItem::YAxisMode(), ResultItem::YAxisTitle(), and ResultItem::YLimit().
Referenced by Plot().
PlotProfileSet()
bool GeneralChart::PlotProfileSet (Elemental_Profile_Set * elementalprofileset, const QString & title)
Definition at line 344 of file generalchart.cpp.
References chart, counter, Elemental_Profile_Set::GetElementNames(), Elemental_Profile_Set::GetMaximum(), Elemental_Profile_Set::GetMinimum(), high, log, result_item, roundDown(), ResultItem::YAxisMode(), and ResultItem::YLimit().
Referenced by Plot().
PlotRangeSet()
bool GeneralChart::PlotRangeSet (RangeSet * rangeset, const QString & title, const QString & x_axis_title, const QString & y_axis_title)
Definition at line 1173 of file generalchart.cpp.
References chart, counter, ResultItem::FixedYLimit(), high, log, low, rangeset, rangeset_with_observed, result_item, ResultItem::Type(), ResultItem::YAxisMode(), and ResultItem::YLimit().
Referenced by Plot().
PlotRegression()
bool GeneralChart::PlotRegression (MultipleLinearRegression * timeseriesset, const QString & independent_var) private
Definition at line 644 of file generalchart.cpp.
References chart, linear, log, mlr, x, and y.
Referenced by onElementChanged(), and onIndependentChanged().
PlotRegressionSet()
bool GeneralChart::PlotRegressionSet (MultipleLinearRegressionSet * regressionset, const QString & title)
Definition at line 495 of file generalchart.cpp.
References element_combo, independent_combo, onElementChanged(), onIndependentChanged(), and ui.
Referenced by Plot().
PlotScatter() [1/3]
bool GeneralChart::PlotScatter (CMBMatrix * matrix)
Definition at line 777 of file generalchart.cpp.
References chart, and matrix.
Referenced by onDFAPairChanged(), and Plot().
PlotScatter() [2/3]
bool GeneralChart::PlotScatter (CMBVectorSet * vectorset)
Definition at line 828 of file generalchart.cpp.
References chart, counter, result_item, vectorset, ResultItem::XAxisTitle(), and ResultItem::YAxisTitle().
PlotScatter() [3/3]
bool GeneralChart::PlotScatter (CMBVectorSet * vectorset1, CMBVectorSet * vectorset2, const QString & xaxis_title, const QString & yaxistitle)
Definition at line 878 of file generalchart.cpp.
References calculateRotatedEllipsePoints(), chart, counter, CMBVectorSet::max(), CMBVectorSet::min(), x, and y.
PlotTimeSeriesSet()
bool GeneralChart::PlotTimeSeriesSet (CMBTimeSeriesSet * regressionset, const QString & title, const QString & x_axis_title = "", const QString & y_axis_title = "")
Definition at line 1131 of file generalchart.cpp.
References chart.
Referenced by Plot().
PlotTimeSeriesSet_A()
bool GeneralChart::PlotTimeSeriesSet_A (CMBTimeSeriesSet * timeseriesset, const QString & title, const QString & x_axis_title = "", const QString & y_axis_title = "")
Definition at line 1352 of file generalchart.cpp.
References chart, high, CMBTimeSeriesSet::Label(), low, result_item, and ResultItem::YLimit().
PlotTimeSeriesSet_M()
bool GeneralChart::PlotTimeSeriesSet_M (CMBTimeSeriesSet * timeseriesset, const QString & title, const QString & x_axis_title = "", const QString & y_axis_title = "")
Definition at line 1286 of file generalchart.cpp.
References chart, and CMBTimeSeriesSet::Label().
Referenced by Plot().
PlotTimeSeriesSet_Stacked()
bool GeneralChart::PlotTimeSeriesSet_Stacked (CMBTimeSeriesSet * timeseriesset, const QString & title, const QString & x_axis_title, const QString & y_axis_title = "")
Definition at line 1400 of file generalchart.cpp.
References chart, and CMBTimeSeriesSet::Label().
Referenced by Plot().
PlotVector()
bool GeneralChart::PlotVector (CMBVector * profile, const QString & title)
Definition at line 184 of file generalchart.cpp.
References ResultItem::AbsValue(), chart, counter, CMBVector::Labels(), log, ResultItem::Name(), result_item, roundDown(), ResultItem::XAxisTitle(), ResultItem::YAxisMode(), and ResultItem::YAxisTitle().
Referenced by onPairChanged(), and Plot().
PlotVectorSet()
bool GeneralChart::PlotVectorSet (CMBVectorSet * profile, const QString & title)
Definition at line 163 of file generalchart.cpp.
References element_combo, onPairChanged(), and ui.
Referenced by Plot().
PlotVectorSetSet()
bool GeneralChart::PlotVectorSetSet (CMBVectorSetSet * profile, const QString & title)
Definition at line 138 of file generalchart.cpp.
References onDFAPairChanged(), source1_combo, source2_combo, and ui.
Referenced by Plot().
Member Data Documentation
chart
Chart* GeneralChart::chart private
Definition at line 57 of file generalchart.h.
Referenced by GeneralChart(), on_Exporttopng(), onDFAPairChanged(), onPairChanged(), PlotContribution(), PlotDistribution(), PlotMatrix(), PlotMCMCSamples(), PlotPredictedConcentration(), PlotProfileSet(), PlotRangeSet(), PlotRegression(), PlotScatter(), PlotScatter(), PlotScatter(), PlotTimeSeriesSet(), PlotTimeSeriesSet_A(), PlotTimeSeriesSet_M(), PlotTimeSeriesSet_Stacked(), and PlotVector().
chartView
ChartView* GeneralChart::chartView private
Definition at line 58 of file generalchart.h.
Referenced by GeneralChart(), on_Exporttopng(), Plot(), and PlotContribution().
element_combo
QComboBox* GeneralChart::element_combo private
Definition at line 59 of file generalchart.h.
Referenced by InitializeDistributions(), InitializeMCMCSamples(), onDistributionsVariableChanged(), onElementChanged(), onIndependentChanged(), onMCMCVariableChanged(), onPairChanged(), PlotRegressionSet(), and PlotVectorSet().
independent_combo
QComboBox* GeneralChart::independent_combo private
Definition at line 62 of file generalchart.h.
Referenced by onElementChanged(), onIndependentChanged(), and PlotRegressionSet().
result_item
ResultItem* GeneralChart::result_item =nullptr private
Definition at line 64 of file generalchart.h.
Referenced by onDFAPairChanged(), onDistributionsVariableChanged(), onElementChanged(), onIndependentChanged(), onMCMCVariableChanged(), onPairChanged(), Plot(), PlotDistribution(), PlotMatrix(), PlotPredictedConcentration(), PlotProfileSet(), PlotRangeSet(), PlotScatter(), PlotTimeSeriesSet_A(), and PlotVector().
source1_combo
QComboBox* GeneralChart::source1_combo private
Definition at line 60 of file generalchart.h.
Referenced by onDFAPairChanged(), and PlotVectorSetSet().
source2_combo
QComboBox* GeneralChart::source2_combo private
Definition at line 61 of file generalchart.h.
Referenced by onDFAPairChanged(), and PlotVectorSetSet().
ui
Ui::GeneralChart* GeneralChart::ui private
Definition at line 56 of file generalchart.h.
Referenced by GeneralChart(), ~GeneralChart(), InitializeDistributions(), InitializeMCMCSamples(), PlotRegressionSet(), PlotVectorSet(), and PlotVectorSetSet().
The documentation for this class was generated from the following files:
generalchart.h
generalchart.cpp