SedSat3: MultipleLinearRegressionSet Class Reference
MultipleLinearRegressionSet Class Reference
#include </home/runner/work/SedSat3/SedSat3/multiplelinearregressionset.h>
Public Member Functions
MultipleLinearRegressionSet ()
MultipleLinearRegressionSet (const MultipleLinearRegressionSet &mp)
MultipleLinearRegressionSet & operator= (const MultipleLinearRegressionSet &mp)
string ToString () const override
Convert object to string representation.
QJsonObject toJsonObject () const override
Serialize object to JSON format.
bool ReadFromJsonObject (const QJsonObject &jsonobject) override
Deserialize object from JSON format.
bool Append (QString key, const MultipleLinearRegression &MLR)
void SetSource (const string &source)
QTableWidget * ToTable () override
Create a Qt table widget representation of the data.
string Key (int i)
Public Member Functions inherited from Interface
Interface ()
Default constructor.
Interface (const Interface &intf)
Copy constructor.
Interface & operator= (const Interface &intf)
Assignment operator.
virtual bool writetofile (QFile *file)
Write object data to a file.
virtual bool Read (const QStringList &strlist)
Parse object data from a string list.
string GetNotes () const
Get the notes/annotations associated with this object.
void SetNotes (const string &note)
Set the notes for this object, replacing any existing notes.
void AppendtoNotes (const string &note)
Append a note to existing notes.
void ClearNotes ()
Clear all notes associated with this object.
void SetLimit (_range lowhigh, const double &value)
Set upper or lower limit for value highlighting.
void SetOption (options_key opt, bool val)
Set a configuration option.
bool Option (options_key opt)
Get the current value of a configuration option.
options & GetOptions ()
Get reference to the options structure.
QString XAxisLabel () const
Get the X-axis label.
QString YAxisLabel () const
Get the Y-axis label.
bool SetXAxisLabel (const QString &label)
Set the X-axis label.
bool SetYAxisLabel (const QString &label)
Set the Y-axis label.
Private Attributes
string Source
Additional Inherited Members
Public Attributes inherited from Interface
double lowlimit
Lower threshold for value highlighting (when enabled)
double highlimit
Upper threshold for value highlighting (when enabled)
bool highlightoutsideoflimit = false
Flag indicating whether to highlight values outside defined limits.
Detailed Description
Examples
/home/runner/work/SedSat3/SedSat3/src/elemental_profile.cpp.
Definition at line 7 of file multiplelinearregressionset.h.
Constructor & Destructor Documentation
MultipleLinearRegressionSet() [1/2]
MultipleLinearRegressionSet::MultipleLinearRegressionSet ()
Definition at line 3 of file multiplelinearregressionset.cpp.
MultipleLinearRegressionSet() [2/2]
MultipleLinearRegressionSet::MultipleLinearRegressionSet (const MultipleLinearRegressionSet & mp)
Definition at line 8 of file multiplelinearregressionset.cpp.
References Source.
Member Function Documentation
Append()
bool MultipleLinearRegressionSet::Append (QString key, const MultipleLinearRegression & MLR)
Definition at line 39 of file multiplelinearregressionset.cpp.
Key()
string MultipleLinearRegressionSet::Key (int i)
Definition at line 100 of file multiplelinearregressionset.cpp.
References counter.
Referenced by OmSizeCorrectionTableModel::columnCount(), OmSizeCorrectionTableModel::data(), OmSizeCorrectionTableModel::headerData(), and OmSizeCorrectionTableModel::setData().
operator=()
MultipleLinearRegressionSet & MultipleLinearRegressionSet::operator= (const MultipleLinearRegressionSet & mp)
Definition at line 12 of file multiplelinearregressionset.cpp.
References Interface::operator=(), and Source.
ReadFromJsonObject()
bool MultipleLinearRegressionSet::ReadFromJsonObject (const QJsonObject & jsonobject) override virtual
Deserialize object from JSON format.
Parameters
jsonobject The JSON object to read from
Returns
true if deserialization was successful, false otherwise
Pure virtual method for JSON deserialization. Derived classes must implement this to reconstruct their data structure from a JSON object.
Warning
Implementations should validate JSON structure and handle missing fields gracefully
Reimplemented from Interface.
Definition at line 28 of file multiplelinearregressionset.cpp.
References MultipleLinearRegression::ReadFromJsonObject().
SetSource()
void MultipleLinearRegressionSet::SetSource (const string & source) inline
Definition at line 17 of file multiplelinearregressionset.h.
References Source.
toJsonObject()
QJsonObject MultipleLinearRegressionSet::toJsonObject () const override virtual
Serialize object to JSON format.
Returns
QJsonObject containing the serialized data
Pure virtual method for JSON serialization. Derived classes must implement this to convert their data structure to a JSON object suitable for saving to .json files or transmitting over network.
Note
The JSON structure is determined by the derived class
Reimplemented from Interface.
Definition at line 19 of file multiplelinearregressionset.cpp.
ToString()
string MultipleLinearRegressionSet::ToString () const override virtual
Convert object to string representation.
Returns
String representation of the object's data
Pure virtual method that must be implemented by derived classes to provide a human-readable string representation of their data. Typically used for text file export or debugging.
Note
Format is determined by the derived class implementation
Reimplemented from Interface.
Definition at line 49 of file multiplelinearregressionset.cpp.
References MultipleLinearRegression::ToString().
ToTable()
QTableWidget * MultipleLinearRegressionSet::ToTable () override virtual
Create a Qt table widget representation of the data.
Returns
Pointer to a newly allocated QTableWidget displaying the data
Pure virtual method that creates a visual table representation of the object's data suitable for display in the Qt GUI. The returned widget is dynamically allocated and should be managed by Qt's parent-child ownership system.
Note
Caller does not need to delete the returned widget if added to a parent
Highlighting based on limit settings is applied if enabled
Reimplemented from Interface.
Definition at line 61 of file multiplelinearregressionset.cpp.
Member Data Documentation
Source
string MultipleLinearRegressionSet::Source private
Definition at line 22 of file multiplelinearregressionset.h.
Referenced by MultipleLinearRegressionSet(), operator=(), and SetSource().
The documentation for this class was generated from the following files:
multiplelinearregressionset.h
multiplelinearregressionset.cpp