SedSat3: SelectSamples Class Reference
SelectSamples Class Reference
#include </home/runner/work/SedSat3/SedSat3/selectsamples.h>
Public Member Functions
SelectSamples (QWidget *parent=nullptr)
void SetData (SourceSinkData *_data)
~SelectSamples ()
void SetMode (mode _mode)
void comboChanged ()
Private Attributes
Ui::SelectSamples * ui
SourceSinkData * data
mode Mode
Detailed Description
Definition at line 13 of file selectsamples.h.
Constructor & Destructor Documentation
SelectSamples()
SelectSamples::SelectSamples (QWidget * parent = nullptr) explicit
Definition at line 6 of file selectsamples.cpp.
References comboChanged(), and ui.
~SelectSamples()
SelectSamples::~SelectSamples ()
Definition at line 14 of file selectsamples.cpp.
References ui.
Member Function Documentation
comboChanged()
void SelectSamples::comboChanged ()
Definition at line 48 of file selectsamples.cpp.
References data, Mode, regressions, samples, SelectSampleDelegate::SetMode(), SelectSampleTableModel::SetSelectedSource(), and ui.
Referenced by SelectSamples().
SetData()
void SelectSamples::SetData (SourceSinkData * _data)
Definition at line 19 of file selectsamples.cpp.
References data, SourceSinkData::GetTargetGroup(), Mode, regressions, samples, SelectSampleDelegate::SetMode(), SelectSampleTableModel::SetSelectedSource(), and ui.
Referenced by MainWindow::onIncludeExcludeSample(), and MainWindow::onOMSizeCorrection().
SetMode()
void SelectSamples::SetMode (mode _mode) inline
Definition at line 21 of file selectsamples.h.
References Mode.
Referenced by MainWindow::onIncludeExcludeSample(), and MainWindow::onOMSizeCorrection().
Member Data Documentation
data
SourceSinkData* SelectSamples::data private
Definition at line 24 of file selectsamples.h.
Referenced by comboChanged(), and SetData().
Mode
mode SelectSamples::Mode private
Definition at line 25 of file selectsamples.h.
Referenced by comboChanged(), SetData(), and SetMode().
ui
Ui::SelectSamples* SelectSamples::ui private
Definition at line 23 of file selectsamples.h.
Referenced by SelectSamples(), ~SelectSamples(), comboChanged(), and SetData().
The documentation for this class was generated from the following files:
selectsamples.h
selectsamples.cpp