SedSat3: OmSizeCorrectionTableModel Class Reference
OmSizeCorrectionTableModel Class Reference
#include </home/runner/work/SedSat3/SedSat3/omsizecorrectiontablemodel.h>
Public Member Functions
OmSizeCorrectionTableModel (MultipleLinearRegressionSet *MLRset, QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
void editCompleted (const QString &)
Public Attributes
MultipleLinearRegressionSet * MLRset
Detailed Description
Definition at line 8 of file omsizecorrectiontablemodel.h.
Constructor & Destructor Documentation
OmSizeCorrectionTableModel()
OmSizeCorrectionTableModel::OmSizeCorrectionTableModel (MultipleLinearRegressionSet * MLRset, QObject * parent = nullptr)
Definition at line 3 of file omsizecorrectiontablemodel.cpp.
References MLRset.
Member Function Documentation
columnCount()
int OmSizeCorrectionTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 11 of file omsizecorrectiontablemodel.cpp.
References MultipleLinearRegressionSet::Key(), and MLRset.
data()
QVariant OmSizeCorrectionTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 18 of file omsizecorrectiontablemodel.cpp.
References MultipleLinearRegressionSet::Key(), mlr, and MLRset.
editCompleted()
void OmSizeCorrectionTableModel::editCompleted (const QString &)
Referenced by setData().
flags()
Qt::ItemFlags OmSizeCorrectionTableModel::flags (const QModelIndex & index) const override
Definition at line 148 of file omsizecorrectiontablemodel.cpp.
headerData()
QVariant OmSizeCorrectionTableModel::headerData (int section, Qt::Orientation orientation, int role) const override
Definition at line 82 of file omsizecorrectiontablemodel.cpp.
References MultipleLinearRegressionSet::Key(), and MLRset.
rowCount()
int OmSizeCorrectionTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 7 of file omsizecorrectiontablemodel.cpp.
References MLRset.
setData()
bool OmSizeCorrectionTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 123 of file omsizecorrectiontablemodel.cpp.
References editCompleted(), MultipleLinearRegressionSet::Key(), mlr, and MLRset.
Member Data Documentation
MLRset
MultipleLinearRegressionSet* OmSizeCorrectionTableModel::MLRset
Definition at line 22 of file omsizecorrectiontablemodel.h.
Referenced by OmSizeCorrectionTableModel(), columnCount(), data(), headerData(), rowCount(), and setData().
The documentation for this class was generated from the following files:
omsizecorrectiontablemodel.h
omsizecorrectiontablemodel.cpp