SedSat3: Results Class Reference
Results Class Reference
#include </home/runner/work/SedSat3/SedSat3/results.h>
Public Member Functions
Results ()
Results (const Results &rhs)
Results & operator= (const Results &rhs)
void Append (const ResultItem &)
void SetName (const string &_name)
bool ReadFromJson (const QJsonObject &jsonobject)
string GetName ()
QJsonObject toJsonObject ()
void SetError (const string &_error)
void AppendError (const string &_error)
string Error ()
Private Attributes
string name
string error
Detailed Description
Definition at line 14 of file results.h.
Constructor & Destructor Documentation
Results() [1/2]
Results::Results ()
Definition at line 9 of file results.cpp.
Results() [2/2]
Results::Results (const Results & rhs)
Definition at line 14 of file results.cpp.
References name, and string.
Member Function Documentation
Append()
void Results::Append (const ResultItem & ritem)
Definition at line 25 of file results.cpp.
References ResultItem::Name().
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteGA(), Conductor::ExecuteGA_FixedProfile(), Conductor::ExecuteGA_NoTargets(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardt(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteMLR(), Conductor::ExecuteOMSizeCorrect(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), and SourceSinkData::MCMC().
AppendError()
void Results::AppendError (const string & _error) inline
Definition at line 26 of file results.h.
References error.
Referenced by SourceSinkData::MCMC().
Error()
string Results::Error () inline
Definition at line 27 of file results.h.
References error.
Referenced by Conductor::ExecuteCMBBayesian().
GetName()
string Results::GetName () inline
Definition at line 23 of file results.h.
References name.
Referenced by MainWindow::Execute().
operator=()
Results & Results::operator= (const Results & rhs)
Definition at line 18 of file results.cpp.
References name.
ReadFromJson()
bool Results::ReadFromJson (const QJsonObject & jsonobject)
Definition at line 41 of file results.cpp.
References contribution, counter, dfa_vectorsetset, distribution, distribution_with_observed, elemental_profile_set, Interface::GetOptions(), high, log, low, matrix, matrix1vs1, mcmc_samples, mlrset, normal, predicted_concentration, rangeset, rangeset_with_observed, Elemental_Profile::ReadFromJsonObject(), CMBMatrix::ReadFromJsonObject(), CMBTimeSeriesSet::ReadFromJsonObject(), CMBVector::ReadFromJsonObject(), CMBVectorSet::ReadFromJsonObject(), CMBVectorSetSet::ReadFromJsonObject(), Elemental_Profile_Set::ReadFromJsonObject(), samples, ResultItem::SetAbsoluteValue(), CMBMatrix::SetBooleanValue(), Interface::SetLimit(), ResultItem::SetName(), Interface::SetOption(), ResultItem::SetResult(), ResultItem::SetShowAsString(), ResultItem::SetShowGraph(), ResultItem::SetShowTable(), ResultItem::SetType(), ResultItem::SetXAxisMode(), ResultItem::setXAxisTitle(), ResultItem::SetYAxisMode(), ResultItem::setYAxisTitle(), ResultItem::SetYLimit(), single_column_x, stacked_bar_chart, timeseries_set, vector, vectorset_groups, options::X_suffix, and options::Y_suffix.
Referenced by MainWindow::LoadModel().
SetError()
void Results::SetError (const string & _error) inline
Definition at line 25 of file results.h.
References error.
Referenced by SourceSinkData::MCMC().
SetName()
void Results::SetName (const string & _name) inline
Definition at line 21 of file results.h.
References name.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteErrorAnalysis(), Conductor::ExecuteGA(), Conductor::ExecuteGA_FixedProfile(), Conductor::ExecuteGA_NoTargets(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardt(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteMLR(), Conductor::ExecuteOMSizeCorrect(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), and SourceSinkData::MCMC().
toJsonObject()
QJsonObject Results::toJsonObject ()
Definition at line 30 of file results.cpp.
References ResultItem::Result(), and Interface::toJsonObject().
Referenced by MainWindow::buildResultsJson().
Member Data Documentation
error
string Results::error private
Definition at line 30 of file results.h.
Referenced by AppendError(), Error(), and SetError().
name
string Results::name private
Definition at line 29 of file results.h.
Referenced by Results(), GetName(), operator=(), and SetName().
The documentation for this class was generated from the following files:
results.h
results.cpp