SedSat3: PlotWindow Class Reference
PlotWindow Class Reference
#include </home/runner/work/SedSat3/SedSat3/plotwindow.h>
Public Member Functions
PlotWindow (QWidget *parent=nullptr)
~PlotWindow ()
SourceSinkData * Data ()
GeneralChartPlotter * Plotter ()
Private Attributes
Ui::PlotWindow * ui
GeneralChartPlotter * plot = nullptr
Detailed Description
Definition at line 18 of file plotwindow.h.
Constructor & Destructor Documentation
PlotWindow()
PlotWindow::PlotWindow (QWidget * parent = nullptr) explicit
Definition at line 6 of file plotwindow.cpp.
References plot, and ui.
~PlotWindow()
PlotWindow::~PlotWindow ()
Definition at line 23 of file plotwindow.cpp.
References ui.
Member Function Documentation
Data()
SourceSinkData * PlotWindow::Data ()
Definition at line 28 of file plotwindow.cpp.
References Data().
Referenced by Data().
Plotter()
GeneralChartPlotter * PlotWindow::Plotter () inline
Definition at line 27 of file plotwindow.h.
References plot.
Referenced by MainWindow::showdistributionsforelements().
Member Data Documentation
plot
GeneralChartPlotter* PlotWindow::plot = nullptr private
Definition at line 34 of file plotwindow.h.
Referenced by PlotWindow(), and Plotter().
ui
Ui::PlotWindow* PlotWindow::ui private
Definition at line 32 of file plotwindow.h.
Referenced by PlotWindow(), and ~PlotWindow().
The documentation for this class was generated from the following files:
plotwindow.h
plotwindow.cpp