SedSat3: SelectSampleTableModel Class Reference
SelectSampleTableModel Class Reference
#include </home/runner/work/SedSat3/SedSat3/selectsampletablemodel.h>
Public Member Functions
SelectSampleTableModel (SourceSinkData *Data, QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
void SetSelectedSource (const string &group)
Elemental_Profile * GetProfileSet (int row)
Elemental_Profile * GetProfileSet (int row) const
void editCompleted (const QString &)
Public Attributes
SourceSinkData * Data
Private Attributes
string selectedSource
Detailed Description
Definition at line 9 of file selectsampletablemodel.h.
Constructor & Destructor Documentation
SelectSampleTableModel()
SelectSampleTableModel::SelectSampleTableModel (SourceSinkData * Data, QObject * parent = nullptr)
Definition at line 3 of file selectsampletablemodel.cpp.
References Data.
Member Function Documentation
columnCount()
int SelectSampleTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 11 of file selectsampletablemodel.cpp.
data()
QVariant SelectSampleTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 15 of file selectsampletablemodel.cpp.
References Data, Interface::GetNotes(), GetProfileSet(), SourceSinkData::GetSampleNames(), Elemental_Profile::IsIncludedInAnalysis(), and selectedSource.
editCompleted()
void SelectSampleTableModel::editCompleted (const QString &)
Referenced by setData().
flags()
Qt::ItemFlags SelectSampleTableModel::flags (const QModelIndex & index) const override
Definition at line 95 of file selectsampletablemodel.cpp.
GetProfileSet() [1/2]
Elemental_Profile * SelectSampleTableModel::GetProfileSet (int row)
Definition at line 47 of file selectsampletablemodel.cpp.
References Data, SourceSinkData::GetSampleNames(), and selectedSource.
Referenced by data(), and setData().
GetProfileSet() [2/2]
Elemental_Profile * SelectSampleTableModel::GetProfileSet (int row) const
Definition at line 52 of file selectsampletablemodel.cpp.
References Data, SourceSinkData::GetSampleNames(), and selectedSource.
headerData()
QVariant SelectSampleTableModel::headerData (int section, Qt::Orientation orientation, int role) const override
Definition at line 56 of file selectsampletablemodel.cpp.
rowCount()
int SelectSampleTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 7 of file selectsampletablemodel.cpp.
References Data, and selectedSource.
setData()
bool SelectSampleTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 77 of file selectsampletablemodel.cpp.
References editCompleted(), GetProfileSet(), and Elemental_Profile::SetIncludedInAnalysis().
SetSelectedSource()
void SelectSampleTableModel::SetSelectedSource (const string & group) inline
Definition at line 24 of file selectsampletablemodel.h.
References selectedSource.
Referenced by SelectSamples::comboChanged(), and SelectSamples::SetData().
Member Data Documentation
Data
SourceSinkData* SelectSampleTableModel::Data
Definition at line 23 of file selectsampletablemodel.h.
Referenced by SelectSampleTableModel(), data(), GetProfileSet(), GetProfileSet(), and rowCount().
selectedSource
string SelectSampleTableModel::selectedSource private
Definition at line 13 of file selectsampletablemodel.h.
Referenced by data(), GetProfileSet(), GetProfileSet(), rowCount(), and SetSelectedSource().
The documentation for this class was generated from the following files:
selectsampletablemodel.h
selectsampletablemodel.cpp