SedSat3: ResultsWindow Class Reference
ResultsWindow Class Reference
#include </home/runner/work/SedSat3/SedSat3/resultswindow.h>
Public Member Functions
ResultsWindow (QWidget *parent=nullptr)
void AppendText (const string &text)
void AppendResult (const ResultItem &resultitem)
~ResultsWindow ()
void SetResults (Results *res)
void on_result_graph_clicked ()
void on_result_export_clicked ()
void on_result_table_clicked ()
Private Attributes
Ui::ResultsWindow * ui
Results * results = nullptr
int result_item_counter = 0
Detailed Description
Definition at line 14 of file resultswindow.h.
Constructor & Destructor Documentation
ResultsWindow()
ResultsWindow::ResultsWindow (QWidget * parent = nullptr) explicit
Definition at line 13 of file resultswindow.cpp.
References ui.
~ResultsWindow()
ResultsWindow::~ResultsWindow ()
Definition at line 21 of file resultswindow.cpp.
References ui.
Member Function Documentation
AppendResult()
void ResultsWindow::AppendResult (const ResultItem & resultitem)
Definition at line 31 of file resultswindow.cpp.
References ResultItem::Name(), on_result_export_clicked(), on_result_graph_clicked(), on_result_table_clicked(), ResultItem::Result(), result_item_counter, ResultItem::ShowAsString(), ResultItem::ShowGraph(), ResultItem::ShowTable(), Interface::ToString(), and ui.
Referenced by MainWindow::Execute(), and MainWindow::on_old_result_requested().
AppendText()
void ResultsWindow::AppendText (const string & text)
on_result_export_clicked()
void ResultsWindow::on_result_export_clicked ()
Definition at line 134 of file resultswindow.cpp.
References results.
Referenced by AppendResult().
on_result_graph_clicked()
void ResultsWindow::on_result_graph_clicked ()
Definition at line 109 of file resultswindow.cpp.
References GeneralChart::Plot(), and results.
Referenced by AppendResult().
on_result_table_clicked()
void ResultsWindow::on_result_table_clicked ()
Definition at line 120 of file resultswindow.cpp.
References results, and ResultTableViewer::SetTable().
Referenced by AppendResult().
SetResults()
void ResultsWindow::SetResults (Results * res) inline
Definition at line 23 of file resultswindow.h.
References results.
Referenced by MainWindow::Execute(), and MainWindow::on_old_result_requested().
Member Data Documentation
result_item_counter
int ResultsWindow::result_item_counter = 0 private
Definition at line 28 of file resultswindow.h.
Referenced by AppendResult().
results
Results* ResultsWindow::results = nullptr private
Definition at line 27 of file resultswindow.h.
Referenced by on_result_export_clicked(), on_result_graph_clicked(), on_result_table_clicked(), and SetResults().
ui
Ui::ResultsWindow* ResultsWindow::ui private
Definition at line 26 of file resultswindow.h.
Referenced by ResultsWindow(), ~ResultsWindow(), and AppendResult().
The documentation for this class was generated from the following files:
resultswindow.h
resultswindow.cpp