SedSat3: cmbmatrix.h File Reference
cmbmatrix.h File Reference
#include "Matrix.h"
#include "interface.h"
#include "range.h"
#include "cmbvector.h"
Classes
class CMBMatrix
Matrix class with labeled rows and columns for Chemical Mass Balance analysis.
Functions
CMBVector operator* (const CMBMatrix &M, const CMBVector &V)
Matrix-vector multiplication operator.
Function Documentation
operator*()
CMBVector operator* (const CMBMatrix & M, const CMBVector & V)
Matrix-vector multiplication operator.
Multiplies a CMBMatrix by a CMBVector, preserving row labels in the result.
Parameters
M Matrix (left operand)
V Vector (right operand)
Returns
Resulting vector with row labels from matrix M
Definition at line 189 of file cmbmatrix.cpp.
References CMBMatrix::RowLabels(), CMBVector::SetLabels(), CMBMatrix::toMatrix(), and CMBVector::toVector().