SedSat3: cmbmatrix.cpp File Reference
cmbmatrix.cpp File Reference
#include "cmbmatrix.h"
#include "QJsonArray"
#include "Vector.h"
#include <QFile>
Functions
CMBVector operator* (const CMBMatrix &M, const CMBVector &V)
Matrix-vector multiplication operator.
Function Documentation
operator*()
CMBVector operator* (const CMBMatrix & M, const CMBVector & V)
Matrix-vector multiplication operator.
Multiplies a CMBMatrix by a CMBVector, preserving row labels in the result.
Parameters
M Matrix (left operand)
V Vector (right operand)
Returns
Resulting vector with row labels from matrix M
Definition at line 189 of file cmbmatrix.cpp.
References CMBMatrix::RowLabels(), CMBVector::SetLabels(), CMBMatrix::toMatrix(), and CMBVector::toVector().