SedSat3: GA/Individual.cpp File Reference
Individual.cpp File Reference
#include "Individual.h"
#include "Binary.h"
#include "DistributionNUnif.h"
#include <cstdlib>
#include "QuickSort.h"
#include <algorithm>
Functions
double GetRndUnif (double xmin, double xmax)
void cross (const CIndividual &I1, const CIndividual &I2, CIndividual &IR1, CIndividual &IR2)
void cross_RC_L (const CIndividual &I1, const CIndividual &I2, CIndividual &IR1, CIndividual &IR2)
void cross2p (const CIndividual &I1, const CIndividual &I2, CIndividual &IR1, CIndividual &IR2)
Function Documentation
cross()
void cross (const CIndividual & I1, const CIndividual & I2, CIndividual & IR1, CIndividual & IR2)
Definition at line 131 of file Individual.cpp.
References code(), cross(), CBinary::decode(), CBinary::extract(), GetRndUnif(), CIndividual::maxrange, CIndividual::minrange, CBinary::nDigits, CIndividual::nParams, CBinary::precision, CIndividual::precision, and CIndividual::x.
Referenced by cross().
cross2p()
void cross2p (const CIndividual & I1, const CIndividual & I2, CIndividual & IR1, CIndividual & IR2)
Definition at line 214 of file Individual.cpp.
References code(), cross2p(), CBinary::decode(), CBinary::extract(), GetRndUnif(), CIndividual::maxrange, CIndividual::minrange, CBinary::nDigits, CIndividual::nParams, CBinary::precision, CIndividual::precision, and CIndividual::x.
Referenced by cross2p().
cross_RC_L()
void cross_RC_L (const CIndividual & I1, const CIndividual & I2, CIndividual & IR1, CIndividual & IR2)
Definition at line 188 of file Individual.cpp.
References GetRndUnif(), CIndividual::nParams, and CIndividual::x.
Referenced by CGA< T >::crossoverRC().
GetRndUnif()
double GetRndUnif (double xmin, double xmax)
Definition at line 126 of file Individual.cpp.
Referenced by cross(), cross2p(), cross_RC_L(), CGA< T >::crossoverRC(), CIndividual::initialize(), and CIndividual::shake().