#!/usr/bin/env python3
"""Generate the command reference chapter of the SedSAT3 CLI user's manual.

The reference is produced from resources/forms_structures.json, the same file
the graphical interface builds its dialogs from and the same file the command
line build validates scripts against. Generating it means the manual cannot
describe a command differently from the way the software accepts it.

    python3 docs/manual/generate-command-reference.py > docs/manual/commands.tex
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCHEMA = os.path.join(HERE, "..", "..", "resources", "forms_structures.json")

# What the user types in a script, rather than the widget the dialog uses.
TYPE_NAMES = {
    "checkBox": r"\texttt{true} / \texttt{false}",
    "spinBox": "whole number",
    "lineEdit": "number or text",
    "comboBox": "name",
    "fileBrowser_Save": "file name",
}

# Where the accepted values come from. Anything beginning with "Items:" lists
# them literally; the rest are filled from the loaded project.
SOURCE_NAMES = {
    "TargetSamplesList": "a target sample name",
    "TargetSamplesList+Blank": "a target sample name, or empty for all",
    "ElementsList": "a constituent name",
    "ElementsList+Blank+OM": "a constituent name, or empty, or the organic matter constituent",
    "ElementsList+Blank+Size": "a constituent name, or empty, or the particle size constituent",
    "SourceList": "a source group name",
}


def rich_text_to_tex(text):
    """Convert the dialog rich text in a description to LaTeX.

    The descriptions are shown in Qt labels, so a few of them use <b> and <i>.
    Convert those rather than escaping them into visible angle brackets, and
    drop any other tag.
    """
    text = re.sub(r"<\s*b\s*>(.*?)<\s*/\s*b\s*>",
                  lambda m: r"\textbf{" + tex(m.group(1)) + "}", text,
                  flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<\s*i\s*>(.*?)<\s*/\s*i\s*>",
                  lambda m: r"\textit{" + tex(m.group(1)) + "}", text,
                  flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<\s*br\s*/?\s*>", " ", text, flags=re.IGNORECASE)
    # Anything left over is split on the remaining tags and escaped.
    parts = re.split(r"(\\textbf\{[^}]*\}|\\textit\{[^}]*\})", text)
    rebuilt = []
    for part in parts:
        if part.startswith(r"\textbf{") or part.startswith(r"\textit{"):
            rebuilt.append(part)
        else:
            rebuilt.append(tex(re.sub(r"<[^>]+>", "", part)))
    return "".join(rebuilt)


def tex(text):
    """Escape the characters LaTeX would otherwise interpret."""
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")]:
        text = text.replace(a, b)
    return text


def describe_values(parameter):
    source = parameter.get("source", "")
    if source.startswith("Items:"):
        return "one of " + ", ".join(
            r"\texttt{" + tex(v.strip()) + "}" for v in source[6:].split(","))
    if source in SOURCE_NAMES:
        return SOURCE_NAMES[source]
    if source:
        return tex(source)
    return ""


def main():
    with open(SCHEMA, encoding="utf-8") as handle:
        schema = json.load(handle)

    out = []
    out.append("% Generated by docs/manual/generate-command-reference.py")
    out.append("% Do not edit by hand; edit resources/forms_structures.json")
    out.append("% and regenerate, so that the manual and the software agree.")
    out.append("")

    for command in sorted(schema, key=str.lower):
        parameters = schema[command]

        out.append(r"\subsection{\texttt{%s}}" % tex(command))
        out.append(r"\label{cmd:%s}" % command.lower().replace(" ", "-")
                   .replace("(", "").replace(")", "").replace(",", ""))
        out.append(r"\index{%s}" % tex(command))
        out.append("")

        for name, parameter in parameters.items():
            if parameter.get("type") == "Description":
                description = parameter.get("default", "").strip()
                if description:
                    out.append(rich_text_to_tex(description))
                    out.append("")

        real = [(n, p) for n, p in parameters.items()
                if p.get("type") != "Description"]

        if not real:
            out.append("This command takes no arguments.")
            out.append("")
            continue

        out.append(r"\begin{argtable}")
        for name, parameter in sorted(real, key=lambda kv: kv[0].lower()):
            kind = TYPE_NAMES.get(parameter.get("type", ""),
                                  tex(parameter.get("type", "")))
            default = parameter.get("default", None)
            default_cell = (r"\texttt{\dq{}" + tex(str(default)) + r"\dq{}}"
                            if default not in (None, "") else "---")
            values = describe_values(parameter)
            out.append(r"\texttt{%s} & %s & %s & %s \\" %
                       (tex(name), kind, default_cell, values if values else "---"))
        out.append(r"\end{argtable}")
        out.append("")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
