SedSat3: GA/Binary.cpp File Reference
Binary.cpp File Reference
#include "Binary.h"
#include "math.h"
#include <iostream>
#include "GADistribution.h"
Functions
CBinary code (double x, double minrange, double maxrange, int precision)
void cross (CBinary &B1, CBinary &B2, int p)
void cross (CBinary &B1, CBinary &B2, std::vector< int > p)
void cross2p (CBinary &B1, CBinary &B2, int p1, int p2)
Function Documentation
code()
CBinary code (double x, double minrange, double maxrange, int precision)
Definition at line 86 of file Binary.cpp.
References CBinary::Digit, log, CBinary::nDigits, CBinary::precision, and x.
Referenced by cross(), cross2p(), and CIndividual::mutate().
cross() [1/2]
void cross (CBinary & B1, CBinary & B2, int p)
Definition at line 142 of file Binary.cpp.
References CBinary::nDigits.
Referenced by CGA< T >::crossover().
cross() [2/2]
void cross (CBinary & B1, CBinary & B2, std::vector< int > p)
Definition at line 162 of file Binary.cpp.
References CBinary::nDigits.
cross2p()
void cross2p (CBinary & B1, CBinary & B2, int p1, int p2)
Definition at line 190 of file Binary.cpp.
References CBinary::nDigits.
Referenced by CGA< T >::crossover().