SedSat3: ProgressWindow Class Reference
ProgressWindow Class Reference
#include </home/arash/Projects/SedSat3/ProgressWindow.h>
Public Member Functions
ProgressWindow (QWidget *parent=Q_NULLPTR, int number_of_panels=1, bool extra_label_and_progressbar=false)
~ProgressWindow ()
void AppendPoint (const double &x, const double &y, int chart=0)
void SetProgress (const double &prog)
void SetProgress2 (const double &prog)
void SetLabel (const QString &label)
void SetYRange (const double &y0, const double &y1, int chart=0)
void SetXRange (const double &x0, const double &x1, int chart=0)
void SetTitle (const QString &title, int chart=0)
void SetXAxisTitle (const QString &title, int chart=0)
void SetYAxisTitle (const QString &title, int chart=0)
void ClearGraph (int chart=0)
void SetChartTitle (int i, const QString &title)
Private Attributes
Ui::ProgressWindow ui
QVector< ChartCollection > ChartItems
QVector< QString > charttitles
Detailed Description
Definition at line 28 of file ProgressWindow.h.
Constructor & Destructor Documentation
ProgressWindow()
ProgressWindow::ProgressWindow (QWidget * parent = Q_NULLPTR, int number_of_panels = 1, bool extra_label_and_progressbar = false)
Definition at line 5 of file ProgressWindow.cpp.
References ChartItems, charttitles, and ui.
~ProgressWindow()
ProgressWindow::~ProgressWindow ()
Definition at line 65 of file ProgressWindow.cpp.
Member Function Documentation
AppendPoint()
void ProgressWindow::AppendPoint (const double & x, const double & y, int chart = 0)
Definition at line 69 of file ProgressWindow.cpp.
References ChartItems, x, and y.
Referenced by SourceSinkData::SolveLevenberg_Marquardt(), and CMCMC< T >::step().
ClearGraph()
void ProgressWindow::ClearGraph (int chart = 0)
Definition at line 89 of file ProgressWindow.cpp.
References ChartItems.
Referenced by SourceSinkData::MCMC_Batch().
SetChartTitle()
void ProgressWindow::SetChartTitle (int i, const QString & title) inline
Definition at line 45 of file ProgressWindow.h.
References ChartItems, and charttitles.
SetLabel()
void ProgressWindow::SetLabel (const QString & label)
Definition at line 106 of file ProgressWindow.cpp.
References ui.
Referenced by SourceSinkData::LM_Batch(), and SourceSinkData::MCMC_Batch().
SetProgress()
void ProgressWindow::SetProgress (const double & prog)
Definition at line 94 of file ProgressWindow.cpp.
References ui.
Referenced by SourceSinkData::BootStrap(), SourceSinkData::BootStrap(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteSourceVerify(), SourceSinkData::LM_Batch(), SourceSinkData::MCMC(), SourceSinkData::SolveLevenberg_Marquardt(), CMCMC< T >::step(), SourceSinkData::StepwiseDiscriminantFunctionAnalysis(), SourceSinkData::StepwiseDiscriminantFunctionAnalysis(), SourceSinkData::StepwiseDiscriminantFunctionAnalysis(), and SourceSinkData::VerifySource().
SetProgress2()
void ProgressWindow::SetProgress2 (const double & prog)
Definition at line 100 of file ProgressWindow.cpp.
References ui.
Referenced by SourceSinkData::MCMC_Batch().
SetTitle()
void ProgressWindow::SetTitle (const QString & title, int chart = 0)
Definition at line 60 of file ProgressWindow.cpp.
References ChartItems.
Referenced by Conductor::ExecuteGA_FixedProfile(), Conductor::ExecuteTestCMBBayesian(), and SourceSinkData::MCMC().
SetXAxisTitle()
void ProgressWindow::SetXAxisTitle (const QString & title, int chart = 0)
Definition at line 129 of file ProgressWindow.cpp.
References ChartItems.
SetXRange()
void ProgressWindow::SetXRange (const double & x0, const double & x1, int chart = 0)
Definition at line 121 of file ProgressWindow.cpp.
References ChartItems.
Referenced by SourceSinkData::SolveLevenberg_Marquardt().
SetYAxisTitle()
void ProgressWindow::SetYAxisTitle (const QString & title, int chart = 0)
Definition at line 133 of file ProgressWindow.cpp.
References ChartItems.
Referenced by Conductor::ExecuteGA_FixedProfile(), Conductor::ExecuteTestCMBBayesian(), and SourceSinkData::MCMC().
SetYRange()
void ProgressWindow::SetYRange (const double & y0, const double & y1, int chart = 0)
Definition at line 113 of file ProgressWindow.cpp.
References ChartItems.
Member Data Documentation
ChartItems
QVector<ChartCollection> ProgressWindow::ChartItems private
Definition at line 54 of file ProgressWindow.h.
Referenced by ProgressWindow(), AppendPoint(), ClearGraph(), SetChartTitle(), SetTitle(), SetXAxisTitle(), SetXRange(), SetYAxisTitle(), and SetYRange().
charttitles
QVector<QString> ProgressWindow::charttitles private
Definition at line 55 of file ProgressWindow.h.
Referenced by ProgressWindow(), and SetChartTitle().
ui
Ui::ProgressWindow ProgressWindow::ui private
Definition at line 53 of file ProgressWindow.h.
Referenced by ProgressWindow(), SetLabel(), SetProgress(), and SetProgress2().
The documentation for this class was generated from the following files:
ProgressWindow.h
ProgressWindow.cpp