SedSat3: AboutDialog Class Reference
AboutDialog Class Reference
Professional about dialog for SedSat3 application.
#include </home/arash/Projects/SedSat3/aboutdialog.h>
Public Member Functions
AboutDialog (QWidget *parent=nullptr)
Constructs the about dialog.
~AboutDialog () override=default
Destructor.
void setVersion (const QString &version)
Sets the application version.
void setBuildDate (const QString &date)
Sets the build date.
void appendText (const QString &text)
Appends additional text to the description area.
void clearText ()
Clears all text from the description area.
Private Member Functions
void setupUI ()
Sets up the dialog UI.
QWidget * createHeader ()
Creates the header section with logo and title.
QWidget * createInfoSection ()
Creates the information section with version and authors.
QTextBrowser * createDescriptionSection ()
Creates the description text browser.
QWidget * createFooter ()
Creates the footer with copyright and buttons.
Private Attributes
QLabel * versionLabel
QLabel * buildDateLabel
QTextBrowser * descriptionBrowser
Detailed Description
Professional about dialog for SedSat3 application.
Displays application information including version, authors, description, and copyright information. Built entirely in code without .ui file.
Definition at line 19 of file aboutdialog.h.
Constructor & Destructor Documentation
AboutDialog()
AboutDialog::AboutDialog (QWidget * parent = nullptr) explicit
Constructs the about dialog.
Parameters
parent Parent widget
Definition at line 7 of file aboutdialog.cpp.
References setupUI().
~AboutDialog()
AboutDialog::~AboutDialog () override default
Destructor.
Member Function Documentation
appendText()
void AboutDialog::appendText (const QString & text)
Appends additional text to the description area.
Parameters
text Text to append
Definition at line 225 of file aboutdialog.cpp.
References descriptionBrowser.
clearText()
void AboutDialog::clearText ()
Clears all text from the description area.
Definition at line 233 of file aboutdialog.cpp.
References descriptionBrowser.
createDescriptionSection()
QTextBrowser * AboutDialog::createDescriptionSection () private
Creates the description text browser.
Returns
Text browser widget
Definition at line 127 of file aboutdialog.cpp.
References descriptionBrowser.
Referenced by setupUI().
createFooter()
QWidget * AboutDialog::createFooter () private
Creates the footer with copyright and buttons.
Returns
Footer widget
Definition at line 155 of file aboutdialog.cpp.
Referenced by setupUI().
createHeader()
QWidget * AboutDialog::createHeader () private
Creates the header section with logo and title.
Returns
Header widget
Definition at line 37 of file aboutdialog.cpp.
Referenced by setupUI().
createInfoSection()
QWidget * AboutDialog::createInfoSection () private
Creates the information section with version and authors.
Returns
Information widget
Definition at line 77 of file aboutdialog.cpp.
References buildDateLabel, and versionLabel.
Referenced by setupUI().
setBuildDate()
void AboutDialog::setBuildDate (const QString & date)
Sets the build date.
Parameters
date Date string (e.g., "December 20, 2025")
Definition at line 217 of file aboutdialog.cpp.
References buildDateLabel.
Referenced by MainWindow::onAboutTriggered().
setupUI()
void AboutDialog::setupUI () private
Sets up the dialog UI.
Definition at line 16 of file aboutdialog.cpp.
References createDescriptionSection(), createFooter(), createHeader(), and createInfoSection().
Referenced by AboutDialog().
setVersion()
void AboutDialog::setVersion (const QString & version)
Sets the application version.
Parameters
version Version string (e.g., "1.1.3")
Definition at line 209 of file aboutdialog.cpp.
References version, and versionLabel.
Referenced by MainWindow::onAboutTriggered().
Member Data Documentation
buildDateLabel
QLabel* AboutDialog::buildDateLabel private
Definition at line 90 of file aboutdialog.h.
Referenced by createInfoSection(), and setBuildDate().
descriptionBrowser
QTextBrowser* AboutDialog::descriptionBrowser private
Definition at line 91 of file aboutdialog.h.
Referenced by appendText(), clearText(), and createDescriptionSection().
versionLabel
QLabel* AboutDialog::versionLabel private
Definition at line 89 of file aboutdialog.h.
Referenced by createInfoSection(), and setVersion().
The documentation for this class was generated from the following files:
aboutdialog.h
aboutdialog.cpp