SedSat3: GenericForm Class Reference
GenericForm Class Reference
#include </home/arash/Projects/SedSat3/genericform.h>
Public Member Functions
GenericForm (QJsonObject *formdata, QWidget *parent, MainWindow *mainwindow)
~GenericForm ()
bool SetCommand (const QString &cmd)
void onProceed ()
void onCancel ()
Public Attributes
QVector< parameter_property > Parameter_Properties
Private Member Functions
MainWindow * mainwindow ()
Private Attributes
QPushButton * buttonOk = nullptr
QPushButton * buttonCancel = nullptr
Ui::GenericForm * ui
QString command
MainWindow * mainWindow =nullptr
Detailed Description
Definition at line 56 of file genericform.h.
Constructor & Destructor Documentation
GenericForm()
GenericForm::GenericForm (QJsonObject * formdata, QWidget * parent, MainWindow * mainwindow) explicit
Definition at line 6 of file genericform.cpp.
References buttonCancel, buttonOk, CheckBox, ComboBox, MainWindow::Data(), parameter_property::DefaultValue, Description, FileBrowserPushButtom::dialog_use, parameter_property::Discription, FileBrowser, SourceSinkData::GetElementNames(), SourceSinkData::GetSampleNames(), parameter_property::InputWidget, LineEdit, mainwindow(), mainWindow, onCancel(), onProceed(), open, Parameter_Properties, save, SourceSinkData::SourceGroupNames(), SpinBox, parameter_property::Type, and ui.
~GenericForm()
GenericForm::~GenericForm ()
Definition at line 182 of file genericform.cpp.
References Parameter_Properties, and ui.
Member Function Documentation
mainwindow()
MainWindow * GenericForm::mainwindow () private
Definition at line 203 of file genericform.cpp.
References mainWindow.
Referenced by GenericForm(), and onProceed().
onCancel()
void GenericForm::onCancel ()
Definition at line 198 of file genericform.cpp.
Referenced by GenericForm().
onProceed()
void GenericForm::onProceed ()
Definition at line 188 of file genericform.cpp.
References command, MainWindow::Execute(), mainwindow(), and Parameter_Properties.
Referenced by GenericForm().
SetCommand()
bool GenericForm::SetCommand (const QString & cmd)
Definition at line 209 of file genericform.cpp.
References command.
Member Data Documentation
buttonCancel
QPushButton* GenericForm::buttonCancel = nullptr private
Definition at line 68 of file genericform.h.
Referenced by GenericForm().
buttonOk
QPushButton* GenericForm::buttonOk = nullptr private
Definition at line 67 of file genericform.h.
Referenced by GenericForm().
command
QString GenericForm::command private
Definition at line 71 of file genericform.h.
Referenced by onProceed(), and SetCommand().
mainWindow
MainWindow* GenericForm::mainWindow =nullptr private
Definition at line 72 of file genericform.h.
Referenced by GenericForm(), and mainwindow().
Parameter_Properties
QVector<parameter_property> GenericForm::Parameter_Properties
Definition at line 62 of file genericform.h.
Referenced by GenericForm(), ~GenericForm(), and onProceed().
ui
Ui::GenericForm* GenericForm::ui private
Definition at line 69 of file genericform.h.
Referenced by GenericForm(), and ~GenericForm().
The documentation for this class was generated from the following files:
genericform.h
genericform.cpp