SedSat3: ResultItem Class Reference
ResultItem Class Reference
#include </home/arash/Projects/SedSat3/resultitem.h>
Public Member Functions
ResultItem ()
Interface * Result () const
void SetResult (Interface *_result)
ResultItem (const ResultItem &rhs)
ResultItem & operator= (const ResultItem &rhs)
void SetName (const string &_name)
string Name () const
void SetType (const result_type &_type)
result_type Type () const
void SetYAxisMode (yaxis_mode mode)
void SetXAxisMode (xaxis_mode mode)
yaxis_mode YAxisMode ()
xaxis_mode XAxisMode ()
void SetShowAsString (bool value)
bool ShowAsString () const
void setXAxisTitle (const string &title)
void setYAxisTitle (const string &title)
void setTableTitle (const string &Title)
string TableTitle ()
string XAxisTitle ()
string YAxisTitle ()
void SetAbsoluteValue (bool val)
bool AbsValue ()
double YLimit (_range highlow)
void SetYLimit (_range highlow, const double &value)
bool FixedYLimit ()
void SetShowTable (bool state)
bool ShowTable () const
void SetShowGraph (bool state)
bool ShowGraph () const
Public Member Functions inherited from Interface
Interface ()
Interface (const Interface &intf)
Interface & operator= (const Interface &intf)
virtual string ToString () const
virtual QJsonObject toJsonObject () const
virtual bool ReadFromJsonObject (const QJsonObject &jsonobject)
virtual bool writetofile (QFile *file)
virtual bool Read (const QStringList &strlist)
virtual QTableWidget * ToTable ()
string GetNotes () const
void SetNotes (const string &note)
void AppendtoNotes (const string &note)
void ClearNotes ()
void SetLimit (_range lowhigh, const double &value)
void SetOption (options_key opt, bool val)
bool Option (options_key opt)
options & GetOptions ()
QString XAxisLabel () const
QString YAxisLabel () const
bool SetXAxisLabel (const QString &label)
bool SetYAxisLabel (const QString &label)
Private Attributes
string name
result_type type
Interface * result = nullptr
yaxis_mode y_axis_mode = yaxis_mode::log
xaxis_mode x_axis_mode = xaxis_mode::real
bool showabsvalue = false
bool showasstring = true
vector< double > YLimits
bool fixYlimit = false
bool showTable = false
bool showGraph = true
string Table_Title
Additional Inherited Members
Public Attributes inherited from Interface
double lowlimit
double highlimit
bool highlightoutsideoflimit = false
Detailed Description
Definition at line 13 of file resultitem.h.
Constructor & Destructor Documentation
ResultItem() [1/2]
ResultItem::ResultItem ()
Definition at line 3 of file resultitem.cpp.
References YLimits.
ResultItem() [2/2]
ResultItem::ResultItem (const ResultItem & rhs)
Definition at line 8 of file resultitem.cpp.
References fixYlimit, name, result, showabsvalue, showasstring, showGraph, showTable, type, x_axis_mode, y_axis_mode, and YLimits.
Member Function Documentation
AbsValue()
bool ResultItem::AbsValue () inline
Definition at line 58 of file resultitem.h.
References showabsvalue.
Referenced by GeneralChart::PlotMatrix(), and GeneralChart::PlotVector().
FixedYLimit()
bool ResultItem::FixedYLimit () inline
Definition at line 74 of file resultitem.h.
References fixYlimit.
Referenced by GeneralChart::PlotRangeSet().
Name()
string ResultItem::Name () const inline
Definition at line 22 of file resultitem.h.
References name.
Referenced by Results::Append(), ResultsWindow::AppendResult(), GeneralChart::Plot(), and GeneralChart::PlotVector().
operator=()
ResultItem & ResultItem::operator= (const ResultItem & rhs)
Definition at line 22 of file resultitem.cpp.
References fixYlimit, name, Interface::operator=(), result, showabsvalue, showasstring, showGraph, showTable, type, x_axis_mode, y_axis_mode, and YLimits.
Result()
Interface * ResultItem::Result () const inline
Definition at line 17 of file resultitem.h.
References result.
Referenced by ResultsWindow::AppendResult(), SourceSinkData::GetObservedvsModeledElementalProfile(), SourceSinkData::GetObservedvsModeledElementalProfile_Isotope(), GeneralChart::onDFAPairChanged(), GeneralChart::onDistributionsVariableChanged(), GeneralChart::onElementChanged(), GeneralChart::onIndependentChanged(), GeneralChart::onMCMCVariableChanged(), GeneralChart::onPairChanged(), GeneralChart::Plot(), GeneralChart::PlotDistribution(), and Results::toJsonObject().
SetAbsoluteValue()
void ResultItem::SetAbsoluteValue (bool val) inline
Definition at line 57 of file resultitem.h.
References showabsvalue.
Referenced by Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), and Results::ReadFromJson().
SetName()
void ResultItem::SetName (const string & _name) inline
Definition at line 21 of file resultitem.h.
References name.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), SourceSinkData::GetCalculatedElementMeans(), SourceSinkData::GetCalculatedElementMu(), SourceSinkData::GetCalculatedElementSigma(), SourceSinkData::GetContribution(), SourceSinkData::GetEstimatedElementMean(), SourceSinkData::GetEstimatedElementMu(), SourceSinkData::GetEstimatedElementSigma(), SourceSinkData::GetMLRResults(), SourceSinkData::GetObservedElementalProfile(), SourceSinkData::GetObservedElementalProfile_Isotope(), SourceSinkData::GetObservedvsModeledElementalProfile(), SourceSinkData::GetObservedvsModeledElementalProfile_Isotope(), SourceSinkData::GetPredictedElementalProfile(), SourceSinkData::GetPredictedElementalProfile_Isotope(), SourceSinkData::GetSourceProfiles(), SourceSinkData::MCMC(), and Results::ReadFromJson().
SetResult()
void ResultItem::SetResult (Interface * _result) inline
Definition at line 18 of file resultitem.h.
References result.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), SourceSinkData::GetCalculatedElementMeans(), SourceSinkData::GetCalculatedElementMu(), SourceSinkData::GetCalculatedElementSigma(), SourceSinkData::GetContribution(), SourceSinkData::GetEstimatedElementMean(), SourceSinkData::GetEstimatedElementMu(), SourceSinkData::GetEstimatedElementSigma(), SourceSinkData::GetObservedElementalProfile(), SourceSinkData::GetObservedElementalProfile_Isotope(), SourceSinkData::GetObservedvsModeledElementalProfile(), SourceSinkData::GetObservedvsModeledElementalProfile_Isotope(), SourceSinkData::GetPredictedElementalProfile(), SourceSinkData::GetPredictedElementalProfile_Isotope(), Elemental_Profile_Set::GetRegressionsAsResult(), SourceSinkData::GetSourceProfiles(), SourceSinkData::MCMC(), and Results::ReadFromJson().
SetShowAsString()
void ResultItem::SetShowAsString (bool value) inline
Definition at line 29 of file resultitem.h.
References showasstring.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), SourceSinkData::GetSourceProfiles(), SourceSinkData::MCMC(), and Results::ReadFromJson().
SetShowGraph()
void ResultItem::SetShowGraph (bool state) inline
Definition at line 80 of file resultitem.h.
References showGraph.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteGA(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSourceVerify(), SourceSinkData::GetSourceProfiles(), and Results::ReadFromJson().
SetShowTable()
void ResultItem::SetShowTable (bool state) inline
Definition at line 78 of file resultitem.h.
References showTable.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteGA(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardt(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), SourceSinkData::GetMLRResults(), SourceSinkData::GetSourceProfiles(), SourceSinkData::MCMC(), and Results::ReadFromJson().
setTableTitle()
void ResultItem::setTableTitle (const string & Title) inline
Definition at line 47 of file resultitem.h.
References Table_Title.
Referenced by Conductor::ExecuteCorrelationMatrix().
SetType()
void ResultItem::SetType (const result_type & _type) inline
Definition at line 23 of file resultitem.h.
References type.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteBracketingAnalysis(), Conductor::ExecuteBracketingAnalysisBatch(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteCorrelationMatrix(), Conductor::ExecuteCovarianceMatrix(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteGA(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteKolmogorovSmirnovIndividual(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteOutlierAnalysis(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), Conductor::ExecuteTestCMBBayesian(), SourceSinkData::GetCalculatedElementMeans(), SourceSinkData::GetCalculatedElementMu(), SourceSinkData::GetCalculatedElementSigma(), SourceSinkData::GetContribution(), SourceSinkData::GetEstimatedElementMean(), SourceSinkData::GetEstimatedElementMu(), SourceSinkData::GetEstimatedElementSigma(), SourceSinkData::GetObservedElementalProfile(), SourceSinkData::GetObservedElementalProfile_Isotope(), SourceSinkData::GetObservedvsModeledElementalProfile(), SourceSinkData::GetObservedvsModeledElementalProfile_Isotope(), SourceSinkData::GetPredictedElementalProfile(), SourceSinkData::GetPredictedElementalProfile_Isotope(), Elemental_Profile_Set::GetRegressionsAsResult(), SourceSinkData::GetSourceProfiles(), SourceSinkData::MCMC(), and Results::ReadFromJson().
SetXAxisMode()
void ResultItem::SetXAxisMode (xaxis_mode mode) inline
Definition at line 26 of file resultitem.h.
References x_axis_mode.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteSourceVerify(), and Results::ReadFromJson().
setXAxisTitle()
void ResultItem::setXAxisTitle (const string & title) inline
Definition at line 31 of file resultitem.h.
References result, and Interface::SetXAxisLabel().
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteSourceVerify(), and Results::ReadFromJson().
SetYAxisMode()
void ResultItem::SetYAxisMode (yaxis_mode mode) inline
Definition at line 25 of file resultitem.h.
References y_axis_mode.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteBoxCox(), Conductor::ExecuteCMBBayesianBatch(), Conductor::ExecuteDFA(), Conductor::ExecuteDFAM(), Conductor::ExecuteDFAOnevsRest(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteKolmogorovSmirnov(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), SourceSinkData::MCMC(), and Results::ReadFromJson().
setYAxisTitle()
void ResultItem::setYAxisTitle (const string & title) inline
Definition at line 39 of file resultitem.h.
References result, and Interface::SetYAxisLabel().
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteANOVA(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteDistributionFitting(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteSourceVerify(), and Results::ReadFromJson().
SetYLimit()
void ResultItem::SetYLimit (_range highlow, const double & value) inline
Definition at line 66 of file resultitem.h.
References fixYlimit, high, and YLimits.
Referenced by SourceSinkData::BootStrap(), Conductor::ExecuteAutoSelect(), Conductor::ExecuteEDP(), Conductor::ExecuteEDPM(), Conductor::ExecuteLevenbergMarquardtBatch(), Conductor::ExecuteSDFA(), Conductor::ExecuteSDFAM(), Conductor::ExecuteSDFAOnevsRest(), Conductor::ExecuteSourceVerify(), SourceSinkData::MCMC(), and Results::ReadFromJson().
ShowAsString()
bool ResultItem::ShowAsString () const inline
Definition at line 30 of file resultitem.h.
References showasstring.
Referenced by ResultsWindow::AppendResult().
ShowGraph()
bool ResultItem::ShowGraph () const inline
Definition at line 81 of file resultitem.h.
References showGraph.
Referenced by ResultsWindow::AppendResult().
ShowTable()
bool ResultItem::ShowTable () const inline
Definition at line 79 of file resultitem.h.
References showTable.
Referenced by ResultsWindow::AppendResult().
TableTitle()
string ResultItem::TableTitle () inline
Definition at line 51 of file resultitem.h.
References Table_Title.
Type()
result_type ResultItem::Type () const inline
Definition at line 24 of file resultitem.h.
References type.
Referenced by GeneralChart::Plot(), GeneralChart::PlotDistribution(), and GeneralChart::PlotRangeSet().
XAxisMode()
xaxis_mode ResultItem::XAxisMode () inline
Definition at line 28 of file resultitem.h.
References x_axis_mode.
XAxisTitle()
string ResultItem::XAxisTitle () inline
Definition at line 55 of file resultitem.h.
References Interface::XAxisLabel().
Referenced by GeneralChart::Plot(), GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotScatter(), and GeneralChart::PlotVector().
YAxisMode()
yaxis_mode ResultItem::YAxisMode () inline
Definition at line 27 of file resultitem.h.
References y_axis_mode.
Referenced by GeneralChart::PlotMatrix(), GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotProfileSet(), GeneralChart::PlotRangeSet(), and GeneralChart::PlotVector().
YAxisTitle()
string ResultItem::YAxisTitle () inline
Definition at line 56 of file resultitem.h.
References Interface::YAxisLabel().
Referenced by GeneralChart::Plot(), GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotScatter(), and GeneralChart::PlotVector().
YLimit()
double ResultItem::YLimit (_range highlow) inline
Definition at line 59 of file resultitem.h.
References high, and YLimits.
Referenced by GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotProfileSet(), GeneralChart::PlotRangeSet(), and GeneralChart::PlotTimeSeriesSet_A().
Member Data Documentation
fixYlimit
bool ResultItem::fixYlimit = false private
Definition at line 91 of file resultitem.h.
Referenced by ResultItem(), FixedYLimit(), operator=(), and SetYLimit().
name
string ResultItem::name private
Definition at line 83 of file resultitem.h.
Referenced by ResultItem(), Name(), operator=(), and SetName().
result
Interface* ResultItem::result = nullptr private
Definition at line 85 of file resultitem.h.
Referenced by ResultItem(), operator=(), Result(), SetResult(), setXAxisTitle(), and setYAxisTitle().
showabsvalue
bool ResultItem::showabsvalue = false private
Definition at line 88 of file resultitem.h.
Referenced by ResultItem(), AbsValue(), operator=(), and SetAbsoluteValue().
showasstring
bool ResultItem::showasstring = true private
Definition at line 89 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetShowAsString(), and ShowAsString().
showGraph
bool ResultItem::showGraph = true private
Definition at line 93 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetShowGraph(), and ShowGraph().
showTable
bool ResultItem::showTable = false private
Definition at line 92 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetShowTable(), and ShowTable().
Table_Title
string ResultItem::Table_Title private
Definition at line 94 of file resultitem.h.
Referenced by setTableTitle(), and TableTitle().
type
result_type ResultItem::type private
Definition at line 84 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetType(), and Type().
x_axis_mode
xaxis_mode ResultItem::x_axis_mode = xaxis_mode::real private
Definition at line 87 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetXAxisMode(), and XAxisMode().
y_axis_mode
yaxis_mode ResultItem::y_axis_mode = yaxis_mode::log private
Definition at line 86 of file resultitem.h.
Referenced by ResultItem(), operator=(), SetYAxisMode(), and YAxisMode().
YLimits
vector<double> ResultItem::YLimits private
Definition at line 90 of file resultitem.h.
Referenced by ResultItem(), ResultItem(), operator=(), SetYLimit(), and YLimit().
The documentation for this class was generated from the following files:
resultitem.h
resultitem.cpp