SedSat3: IndicateSheetsDialog Class Reference
IndicateSheetsDialog Class Reference
#include </home/arash/Projects/SedSat3/indicatesheetsdialog.h>
Public Member Functions
IndicateSheetsDialog (QWidget *parent=nullptr)
~IndicateSheetsDialog ()
void Populate_Table (const QStringList &sheets)
Private Member Functions
void reject ()
void accept ()
void on_radio_button_changed ()
Private Attributes
Ui::IndicateSheetsDialog * ui
QList< QRadioButton * > radio_buttons_sinks
QList< QRadioButton * > radio_buttons_sources
QStringList group_names
Detailed Description
Definition at line 13 of file indicatesheetsdialog.h.
Constructor & Destructor Documentation
IndicateSheetsDialog()
IndicateSheetsDialog::IndicateSheetsDialog (QWidget * parent = nullptr) explicit
Definition at line 9 of file indicatesheetsdialog.cpp.
References accept(), reject(), and ui.
~IndicateSheetsDialog()
IndicateSheetsDialog::~IndicateSheetsDialog ()
Definition at line 18 of file indicatesheetsdialog.cpp.
References ui.
Member Function Documentation
accept()
void IndicateSheetsDialog::accept () private
Definition at line 61 of file indicatesheetsdialog.cpp.
References group_names, and radio_buttons_sinks.
Referenced by IndicateSheetsDialog().
on_radio_button_changed()
void IndicateSheetsDialog::on_radio_button_changed () private
Definition at line 73 of file indicatesheetsdialog.cpp.
References radio_buttons_sinks, and radio_buttons_sources.
Referenced by Populate_Table().
Populate_Table()
void IndicateSheetsDialog::Populate_Table (const QStringList & sheets)
Definition at line 23 of file indicatesheetsdialog.cpp.
References group_names, on_radio_button_changed(), radio_buttons_sinks, radio_buttons_sources, and ui.
reject()
void IndicateSheetsDialog::reject () private
Definition at line 57 of file indicatesheetsdialog.cpp.
Referenced by IndicateSheetsDialog().
Member Data Documentation
group_names
QStringList IndicateSheetsDialog::group_names private
Definition at line 26 of file indicatesheetsdialog.h.
Referenced by accept(), and Populate_Table().
radio_buttons_sinks
QList<QRadioButton*> IndicateSheetsDialog::radio_buttons_sinks private
Definition at line 24 of file indicatesheetsdialog.h.
Referenced by accept(), on_radio_button_changed(), and Populate_Table().
radio_buttons_sources
QList<QRadioButton*> IndicateSheetsDialog::radio_buttons_sources private
Definition at line 25 of file indicatesheetsdialog.h.
Referenced by on_radio_button_changed(), and Populate_Table().
ui
Ui::IndicateSheetsDialog* IndicateSheetsDialog::ui private
Definition at line 23 of file indicatesheetsdialog.h.
Referenced by IndicateSheetsDialog(), ~IndicateSheetsDialog(), and Populate_Table().
The documentation for this class was generated from the following files:
indicatesheetsdialog.h
indicatesheetsdialog.cpp