SedSat3: CMBVectorSetSet Class Reference
CMBVectorSetSet Class Reference
Collection of named CMBVectorSet objects for hierarchical data organization.
#include </home/arash/Projects/SedSat3/cmbvectorsetset.h>
Public Member Functions
CMBVectorSetSet ()
Default constructor - creates an empty vector set set.
CMBVectorSetSet (const CMBVectorSetSet &mp)
Copy constructor.
CMBVectorSetSet & operator= (const CMBVectorSetSet &mp)
Assignment operator.
QJsonObject toJsonObject () const override
Serializes vector set set to JSON format.
bool ReadFromJsonObject (const QJsonObject &jsonobject) override
Deserializes vector set set from JSON format.
string ToString () const override
Converts vector set set to string representation.
QTableWidget * ToTable () override
Creates a QTableWidget for displaying vector set set data.
bool writetofile (QFile *file) override
Writes vector set set to file.
string Label (const string &vectorset, const string &column, int j) const
Gets label at specified position in a column within a vector set.
double valueAt (const string &vectorset, const string &columnlabel, int j) const
Gets value at specified position in a column within a vector set.
CMBVector & GetColumn (const string &vectorset, const string &columnlabel)
Gets reference to a named column vector within a vector set.
void Append (const string &columnlabel, const CMBVectorSet &vectorset)
Adds or replaces a vector set in the collection.
unsigned int MaxSize () const
Finds the maximum size among all vectors in all sets.
double max () const
Finds the maximum value across all vectors in all sets.
double min () const
Finds the minimum value across all vectors in all sets.
Public Member Functions inherited from Interface
Interface ()
Interface (const Interface &intf)
Interface & operator= (const Interface &intf)
virtual bool Read (const QStringList &strlist)
string GetNotes () const
void SetNotes (const string &note)
void AppendtoNotes (const string &note)
void ClearNotes ()
void SetLimit (_range lowhigh, const double &value)
void SetOption (options_key opt, bool val)
bool Option (options_key opt)
options & GetOptions ()
QString XAxisLabel () const
QString YAxisLabel () const
bool SetXAxisLabel (const QString &label)
bool SetYAxisLabel (const QString &label)
Additional Inherited Members
Public Attributes inherited from Interface
double lowlimit
double highlimit
bool highlightoutsideoflimit = false
Detailed Description
Collection of named CMBVectorSet objects for hierarchical data organization.
Manages a two-level hierarchy of vectors: sets of vector sets. Provides JSON serialization and table generation for complex multi-group, multi-variable datasets. Commonly used for organizing discriminant function analysis results across multiple discriminant axes.
Definition at line 17 of file cmbvectorsetset.h.
Constructor & Destructor Documentation
CMBVectorSetSet() [1/2]
CMBVectorSetSet::CMBVectorSetSet ()
Default constructor - creates an empty vector set set.
Definition at line 5 of file cmbvectorsetset.cpp.
CMBVectorSetSet() [2/2]
CMBVectorSetSet::CMBVectorSetSet (const CMBVectorSetSet & mp)
Copy constructor.
Parameters
mp Vector set set to copy from
Definition at line 9 of file cmbvectorsetset.cpp.
Member Function Documentation
Append()
void CMBVectorSetSet::Append (const string & columnlabel, const CMBVectorSet & vectorset)
Adds or replaces a vector set in the collection.
Parameters
columnlabel Name for the vector set
vectorset Vector set to add
Definition at line 134 of file cmbvectorsetset.cpp.
References vectorset.
Referenced by SourceSinkData::DiscriminantFunctionAnalysis().
GetColumn()
CMBVector & CMBVectorSetSet::GetColumn (const string & vectorset, const string & columnlabel)
Gets reference to a named column vector within a vector set.
Parameters
vectorset Name of the vector set
columnlabel Name of the vector column
Returns
Reference to the CMBVector
Definition at line 130 of file cmbvectorsetset.cpp.
References vectorset.
Label()
string CMBVectorSetSet::Label (const string & vectorset, const string & column, int j) const
Gets label at specified position in a column within a vector set.
Parameters
vectorset Name of the vector set
column Name of the vector column within the set
j Index within the column
Returns
Label string, or empty string if not found
Definition at line 116 of file cmbvectorsetset.cpp.
References Label(), and vectorset.
Referenced by Label().
max()
double CMBVectorSetSet::max () const
Finds the maximum value across all vectors in all sets.
Returns
Maximum value found
Definition at line 60 of file cmbvectorsetset.cpp.
MaxSize()
unsigned int CMBVectorSetSet::MaxSize () const
Finds the maximum size among all vectors in all sets.
Returns
Maximum number of elements in any vector
Definition at line 49 of file cmbvectorsetset.cpp.
Referenced by ToTable().
min()
double CMBVectorSetSet::min () const
Finds the minimum value across all vectors in all sets.
Returns
Minimum value found
Definition at line 69 of file cmbvectorsetset.cpp.
operator=()
CMBVectorSetSet & CMBVectorSetSet::operator= (const CMBVectorSetSet & mp)
Assignment operator.
Parameters
mp Vector set set to assign from
Returns
Reference to this vector set set
Definition at line 13 of file cmbvectorsetset.cpp.
References Interface::operator=().
ReadFromJsonObject()
bool CMBVectorSetSet::ReadFromJsonObject (const QJsonObject & jsonobject) override virtual
Deserializes vector set set from JSON format.
Parameters
jsonobject JSON object to read from
Returns
true if successful, false otherwise
Reimplemented from Interface.
Definition at line 28 of file cmbvectorsetset.cpp.
References CMBVectorSet::ReadFromJsonObject().
Referenced by Results::ReadFromJson().
toJsonObject()
QJsonObject CMBVectorSetSet::toJsonObject () const override virtual
Serializes vector set set to JSON format.
Returns
JSON object containing all vector sets with their names as keys
Reimplemented from Interface.
Definition at line 19 of file cmbvectorsetset.cpp.
ToString()
string CMBVectorSetSet::ToString () const override virtual
Converts vector set set to string representation.
Returns
String containing all vector sets with their names
Reimplemented from Interface.
Definition at line 37 of file cmbvectorsetset.cpp.
References CMBVectorSet::ToString().
Referenced by writetofile().
ToTable()
QTableWidget * CMBVectorSetSet::ToTable () override virtual
Creates a QTableWidget for displaying vector set set data.
Generates a table with column pairs for each vector in each set, with hierarchical column headers.
Returns
Pointer to newly created QTableWidget (caller takes ownership)
Reimplemented from Interface.
Definition at line 80 of file cmbvectorsetset.cpp.
References MaxSize(), and vectorset.
valueAt()
double CMBVectorSetSet::valueAt (const string & vectorset, const string & columnlabel, int j) const
Gets value at specified position in a column within a vector set.
Parameters
vectorset Name of the vector set
columnlabel Name of the vector column within the set
j Index within the column
Returns
Value at position j, or 0 if not found
Definition at line 123 of file cmbvectorsetset.cpp.
References valueAt(), and vectorset.
Referenced by valueAt().
writetofile()
bool CMBVectorSetSet::writetofile (QFile * file) override virtual
Writes vector set set to file.
Parameters
file File pointer to write to
Returns
true if successful
Reimplemented from Interface.
Definition at line 110 of file cmbvectorsetset.cpp.
References ToString().
The documentation for this class was generated from the following files:
cmbvectorsetset.h
cmbvectorsetset.cpp