SedSat3: RangeSet Class Reference
RangeSet Class Reference
#include </home/arash/Projects/SedSat3/rangeset.h>
Public Member Functions
RangeSet ()
RangeSet (const RangeSet &rhs)
RangeSet & operator= (const RangeSet &rhs)
QJsonObject toJsonObject () const override
bool ReadFromJsonObject (const QJsonObject &jsonobject) override
string ToString () const override
bool writetofile (QFile *) override
bool Read (const QStringList &strlist) override
QTableWidget * ToTable () override
double maxval ()
double minval ()
Public Member Functions inherited from Interface
Interface ()
Interface (const Interface &intf)
Interface & operator= (const Interface &intf)
string GetNotes () const
void SetNotes (const string &note)
void AppendtoNotes (const string &note)
void ClearNotes ()
void SetLimit (_range lowhigh, const double &value)
void SetOption (options_key opt, bool val)
bool Option (options_key opt)
options & GetOptions ()
QString XAxisLabel () const
QString YAxisLabel () const
bool SetXAxisLabel (const QString &label)
bool SetYAxisLabel (const QString &label)
Additional Inherited Members
Public Attributes inherited from Interface
double lowlimit
double highlimit
bool highlightoutsideoflimit = false
Detailed Description
Definition at line 7 of file rangeset.h.
Constructor & Destructor Documentation
RangeSet() [1/2]
RangeSet::RangeSet ()
Definition at line 4 of file rangeset.cpp.
RangeSet() [2/2]
RangeSet::RangeSet (const RangeSet & rhs)
Definition at line 9 of file rangeset.cpp.
Member Function Documentation
maxval()
double RangeSet::maxval ()
Definition at line 59 of file rangeset.cpp.
References high.
minval()
double RangeSet::minval ()
Definition at line 70 of file rangeset.cpp.
References low.
operator=()
RangeSet & RangeSet::operator= (const RangeSet & rhs)
Definition at line 13 of file rangeset.cpp.
References Interface::operator=().
Read()
bool RangeSet::Read (const QStringList & strlist) override virtual
Reimplemented from Interface.
Definition at line 54 of file rangeset.cpp.
ReadFromJsonObject()
bool RangeSet::ReadFromJsonObject (const QJsonObject & jsonobject) override virtual
Reimplemented from Interface.
Definition at line 28 of file rangeset.cpp.
References Range::ReadFromJsonObject().
toJsonObject()
QJsonObject RangeSet::toJsonObject () const override virtual
Reimplemented from Interface.
Definition at line 19 of file rangeset.cpp.
ToString()
string RangeSet::ToString () const override virtual
Reimplemented from Interface.
Definition at line 38 of file rangeset.cpp.
Referenced by writetofile().
ToTable()
QTableWidget * RangeSet::ToTable () override virtual
Reimplemented from Interface.
Definition at line 82 of file rangeset.cpp.
References high, and low.
writetofile()
bool RangeSet::writetofile (QFile * file) override virtual
Reimplemented from Interface.
Definition at line 48 of file rangeset.cpp.
References ToString().
The documentation for this class was generated from the following files:
rangeset.h
rangeset.cpp