SedSat3: CMBMatrix Class Reference
CMBMatrix Class Reference
Matrix class with labeled rows and columns for Chemical Mass Balance analysis.
#include </home/arash/Projects/SedSat3/cmbmatrix.h>
Public Member Functions
CMBMatrix ()
Default constructor - creates an empty matrix.
CMBMatrix (int n)
Constructs a square matrix with given dimension.
CMBMatrix (int n, int m)
Constructs a rectangular matrix with given dimensions.
CMBMatrix (const CMBMatrix &mp)
Copy constructor.
CMatrix toMatrix () const
Converts to base CMatrix type (without labels)
CMBMatrix & operator= (const CMBMatrix &mp)
Assignment operator.
QJsonObject toJsonObject () const override
Serializes matrix to JSON format.
bool ReadFromJsonObject (const QJsonObject &jsonobject) override
Deserializes matrix from JSON format.
string ToString () const override
Converts matrix to CSV-formatted string.
bool writetofile (QFile *file) override
Writes matrix to file in CSV format.
double valueAt (int i, int j) const
Gets value at specified matrix position.
string ColumnLabel (int i)
Gets column label at specified index.
string RowLabel (int i)
Gets row label at specified index.
void SetColumnLabel (int i, const string &label)
Sets column label at specified index.
void SetRowLabel (int i, const string &label)
Sets row label at specified index.
void SetColumnLabels (const vector< string > &label)
Sets all column labels at once.
void SetRowLabels (const vector< string > &label)
Sets all row labels at once.
QTableWidget * ToTable () override
Creates a QTableWidget for displaying matrix data.
vector< string > RowLabels () const
Gets all row labels.
vector< string > ColumnLabels () const
Gets all column labels.
CMBVector GetRow (const string &rowlabel)
Extracts a row by its label.
CMBVector GetColumn (const string &columnlabel)
Extracts a column by its label.
QStringList RowLabelCategories ()
Gets unique row label categories.
void SetBooleanValue (bool val)
Sets boolean display mode for table widget.
Public Member Functions inherited from Interface
Interface ()
Interface (const Interface &intf)
Interface & operator= (const Interface &intf)
virtual bool Read (const QStringList &strlist)
string GetNotes () const
void SetNotes (const string &note)
void AppendtoNotes (const string &note)
void ClearNotes ()
void SetLimit (_range lowhigh, const double &value)
void SetOption (options_key opt, bool val)
bool Option (options_key opt)
options & GetOptions ()
QString XAxisLabel () const
QString YAxisLabel () const
bool SetXAxisLabel (const QString &label)
bool SetYAxisLabel (const QString &label)
Private Attributes
vector< string > columnlabels
Labels for each column.
vector< string > rowlabels
Labels for each row.
bool boolean_values = false
Display values as Pass/Fail instead of numbers.
Additional Inherited Members
Public Attributes inherited from Interface
double lowlimit
double highlimit
bool highlightoutsideoflimit = false
Detailed Description
Matrix class with labeled rows and columns for Chemical Mass Balance analysis.
Extends CMatrix with string labels for rows and columns, JSON serialization, table widget generation, and specialized operations for CMB calculations. Inherits from both CMatrix (for mathematical operations) and Interface (for I/O and visualization).
Definition at line 18 of file cmbmatrix.h.
Constructor & Destructor Documentation
CMBMatrix() [1/4]
CMBMatrix::CMBMatrix ()
Default constructor - creates an empty matrix.
Definition at line 6 of file cmbmatrix.cpp.
CMBMatrix() [2/4]
CMBMatrix::CMBMatrix (int n)
Constructs a square matrix with given dimension.
Parameters
n Number of rows and columns
Definition at line 20 of file cmbmatrix.cpp.
References columnlabels, and rowlabels.
CMBMatrix() [3/4]
CMBMatrix::CMBMatrix (int n, int m)
Constructs a rectangular matrix with given dimensions.
Parameters
n Number of columns
m Number of rows
Definition at line 25 of file cmbmatrix.cpp.
References columnlabels, and rowlabels.
CMBMatrix() [4/4]
CMBMatrix::CMBMatrix (const CMBMatrix & mp)
Copy constructor.
Parameters
mp Matrix to copy from
Definition at line 11 of file cmbmatrix.cpp.
References columnlabels, Interface::highlightoutsideoflimit, Interface::highlimit, Interface::lowlimit, and rowlabels.
Member Function Documentation
ColumnLabel()
string CMBMatrix::ColumnLabel (int i) inline
Gets column label at specified index.
Parameters
i Column index
Returns
Column label string
Definition at line 97 of file cmbmatrix.h.
References columnlabels.
ColumnLabels()
vector< string > CMBMatrix::ColumnLabels () const inline
Gets all column labels.
Returns
Vector of column label strings
Definition at line 153 of file cmbmatrix.h.
References columnlabels.
Referenced by GetRow().
GetColumn()
CMBVector CMBMatrix::GetColumn (const string & columnlabel)
Extracts a column by its label.
Parameters
columnlabel Label of the column to extract
Returns
CMBVector containing the column values with row labels
Definition at line 214 of file cmbmatrix.cpp.
References columnlabels, RowLabels(), and CMBVector::SetLabels().
GetRow()
CMBVector CMBMatrix::GetRow (const string & rowlabel)
Extracts a row by its label.
Parameters
rowlabel Label of the row to extract
Returns
CMBVector containing the row values with column labels
Definition at line 200 of file cmbmatrix.cpp.
References ColumnLabels(), rowlabels, and CMBVector::SetLabels().
operator=()
CMBMatrix & CMBMatrix::operator= (const CMBMatrix & mp)
Assignment operator.
Parameters
mp Matrix to assign from
Returns
Reference to this matrix
Definition at line 31 of file cmbmatrix.cpp.
References columnlabels, Interface::highlightoutsideoflimit, Interface::highlimit, Interface::lowlimit, and rowlabels.
ReadFromJsonObject()
bool CMBMatrix::ReadFromJsonObject (const QJsonObject & jsonobject) override virtual
Deserializes matrix from JSON format.
Parameters
jsonobject JSON object to read from
Returns
true if successful, false otherwise
Reimplemented from Interface.
Definition at line 67 of file cmbmatrix.cpp.
References columnlabels, and rowlabels.
Referenced by Results::ReadFromJson().
RowLabel()
string CMBMatrix::RowLabel (int i) inline
Gets row label at specified index.
Parameters
i Row index
Returns
Row label string
Definition at line 104 of file cmbmatrix.h.
References rowlabels.
RowLabelCategories()
QStringList CMBMatrix::RowLabelCategories ()
Gets unique row label categories.
Returns
QStringList of unique row labels (no duplicates)
Definition at line 229 of file cmbmatrix.cpp.
References rowlabels.
RowLabels()
vector< string > CMBMatrix::RowLabels () const inline
Gets all row labels.
Returns
Vector of row label strings
Definition at line 147 of file cmbmatrix.h.
References rowlabels.
Referenced by GetColumn(), and operator*().
SetBooleanValue()
void CMBMatrix::SetBooleanValue (bool val) inline
Sets boolean display mode for table widget.
When true, matrix values are displayed as "Pass" (0) or "Fail" (1) in the table widget instead of numeric values.
Parameters
val True to enable boolean display mode
Definition at line 183 of file cmbmatrix.h.
References boolean_values.
Referenced by Conductor::ExecuteBracketingAnalysisBatch(), and Results::ReadFromJson().
SetColumnLabel()
void CMBMatrix::SetColumnLabel (int i, const string & label) inline
Sets column label at specified index.
Parameters
i Column index
label Label string to set
Definition at line 111 of file cmbmatrix.h.
References columnlabels.
Referenced by SourceSinkData::BracketTest(), Elemental_Profile_Set::CalculateCorrelationMatrix(), Elemental_Profile_Set::CalculateCovarianceMatrix(), Elemental_Profile_Set::DetectOutliers(), and SourceSinkData::MCMC_Batch().
SetColumnLabels()
void CMBMatrix::SetColumnLabels (const vector< string > & label) inline
Sets all column labels at once.
Parameters
label Vector of label strings
Definition at line 124 of file cmbmatrix.h.
References columnlabels.
SetRowLabel()
void CMBMatrix::SetRowLabel (int i, const string & label) inline
Sets row label at specified index.
Parameters
i Row index
label Label string to set
Definition at line 118 of file cmbmatrix.h.
References rowlabels.
Referenced by SourceSinkData::BracketTest(), Elemental_Profile_Set::CalculateCorrelationMatrix(), Elemental_Profile_Set::CalculateCovarianceMatrix(), Elemental_Profile_Set::DetectOutliers(), and SourceSinkData::MCMC_Batch().
SetRowLabels()
void CMBMatrix::SetRowLabels (const vector< string > & label) inline
Sets all row labels at once.
Parameters
label Vector of label strings
Definition at line 130 of file cmbmatrix.h.
References rowlabels.
toJsonObject()
QJsonObject CMBMatrix::toJsonObject () const override virtual
Serializes matrix to JSON format.
Returns
JSON object containing matrix data, row labels, and column labels
Reimplemented from Interface.
Definition at line 41 of file cmbmatrix.cpp.
References columnlabels, matrix, rowlabels, and valueAt().
toMatrix()
CMatrix CMBMatrix::toMatrix () const
Converts to base CMatrix type (without labels)
Returns
CMatrix representation
Definition at line 193 of file cmbmatrix.cpp.
Referenced by operator*().
ToString()
string CMBMatrix::ToString () const override virtual
Converts matrix to CSV-formatted string.
Returns
String representation with labels and comma-separated values
Reimplemented from Interface.
Definition at line 101 of file cmbmatrix.cpp.
References columnlabels, rowlabels, and valueAt().
Referenced by writetofile().
ToTable()
QTableWidget * CMBMatrix::ToTable () override virtual
Creates a QTableWidget for displaying matrix data.
Generates a read-only table widget with labeled rows and columns. Highlights cells outside limit range if highlighting is enabled. Displays boolean values as "Pass"/"Fail" if boolean mode is set.
Returns
Pointer to newly created QTableWidget (caller takes ownership)
Reimplemented from Interface.
Definition at line 122 of file cmbmatrix.cpp.
References boolean_values, columnlabels, Interface::highlightoutsideoflimit, Interface::highlimit, Interface::lowlimit, and rowlabels.
valueAt()
double CMBMatrix::valueAt (int i, int j) const
Gets value at specified matrix position.
Parameters
i Row index
j Column index
Returns
Matrix value at position (i,j)
Definition at line 180 of file cmbmatrix.cpp.
Referenced by toJsonObject(), and ToString().
writetofile()
bool CMBMatrix::writetofile (QFile * file) override virtual
Writes matrix to file in CSV format.
Parameters
file File pointer to write to
Returns
true if successful
Reimplemented from Interface.
Definition at line 96 of file cmbmatrix.cpp.
References ToString().
Member Data Documentation
boolean_values
bool CMBMatrix::boolean_values = false private
Display values as Pass/Fail instead of numbers.
Definition at line 188 of file cmbmatrix.h.
Referenced by SetBooleanValue(), and ToTable().
columnlabels
vector<string> CMBMatrix::columnlabels private
Labels for each column.
Definition at line 186 of file cmbmatrix.h.
Referenced by CMBMatrix(), CMBMatrix(), CMBMatrix(), ColumnLabel(), ColumnLabels(), GetColumn(), operator=(), ReadFromJsonObject(), SetColumnLabel(), SetColumnLabels(), toJsonObject(), ToString(), and ToTable().
rowlabels
vector<string> CMBMatrix::rowlabels private
Labels for each row.
Definition at line 187 of file cmbmatrix.h.
Referenced by CMBMatrix(), CMBMatrix(), CMBMatrix(), GetRow(), operator=(), ReadFromJsonObject(), RowLabel(), RowLabelCategories(), RowLabels(), SetRowLabel(), SetRowLabels(), toJsonObject(), ToString(), and ToTable().
The documentation for this class was generated from the following files:
cmbmatrix.h
cmbmatrix.cpp