SedSat3: ResultTableViewer Class Reference
ResultTableViewer Class Reference
#include </home/arash/Projects/SedSat3/resulttableviewer.h>
Public Member Functions
ResultTableViewer (QWidget *parent=nullptr)
void SetTable (QTableWidget *tablewidget)
~ResultTableViewer ()
void on_ExportToCSV ()
Private Attributes
Ui::ResultTableViewer * ui
QTableWidget * tablewidget
Detailed Description
Definition at line 11 of file resulttableviewer.h.
Constructor & Destructor Documentation
ResultTableViewer()
ResultTableViewer::ResultTableViewer (QWidget * parent = nullptr) explicit
Definition at line 6 of file resulttableviewer.cpp.
References on_ExportToCSV(), and ui.
~ResultTableViewer()
ResultTableViewer::~ResultTableViewer ()
Definition at line 19 of file resulttableviewer.cpp.
References ui.
Member Function Documentation
on_ExportToCSV()
void ResultTableViewer::on_ExportToCSV ()
Definition at line 30 of file resulttableviewer.cpp.
References string, and tablewidget.
Referenced by ResultTableViewer().
SetTable()
void ResultTableViewer::SetTable (QTableWidget * tablewidget)
Definition at line 24 of file resulttableviewer.cpp.
References tablewidget, and ui.
Referenced by ResultsWindow::on_result_table_clicked(), and MainWindow::on_show_data_as_table().
Member Data Documentation
tablewidget
QTableWidget* ResultTableViewer::tablewidget private
Definition at line 22 of file resulttableviewer.h.
Referenced by on_ExportToCSV(), and SetTable().
ui
Ui::ResultTableViewer* ResultTableViewer::ui private
Definition at line 21 of file resulttableviewer.h.
Referenced by ResultTableViewer(), ~ResultTableViewer(), and SetTable().
The documentation for this class was generated from the following files:
resulttableviewer.h
resulttableviewer.cpp