SedSat3: cmbvector.h File Reference
cmbvector.h File Reference
#include "Vector.h"
#include "interface.h"
#include "range.h"
Classes
class CMBVector
Vector class with string labels for Chemical Mass Balance analysis.
Functions
CMBVector operator+ (const CMBVector &, const CMBVector &)
Vector addition operator.
CMBVector operator+ (double, const CMBVector &)
Scalar-vector addition operator (scalar + vector)
CMBVector operator+ (const CMBVector &, double)
Vector-scalar addition operator (vector + scalar)
CMBVector operator- (const CMBVector &, const CMBVector &)
Vector subtraction operator.
CMBVector operator- (double, const CMBVector &)
Scalar-vector subtraction operator (scalar - vector)
CMBVector operator- (const CMBVector &, double)
Vector-scalar subtraction operator (vector - scalar)
CMBVector operator* (const CMBVector &, const CMBVector &)
Element-wise vector multiplication operator.
CMBVector operator* (double, const CMBVector &)
Scalar-vector multiplication operator.
CMBVector operator/ (const CMBVector &, double)
Vector-scalar division operator.
Function Documentation
operator*() [1/2]
CMBVector operator* (const CMBVector & V1, const CMBVector & V2)
Element-wise vector multiplication operator.
Parameters
V1 First vector
V2 Second vector
Returns
Element-wise product with labels from V1
Definition at line 357 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator*() [2/2]
CMBVector operator* (double d, const CMBVector & V1)
Scalar-vector multiplication operator.
Parameters
d Scalar value
V1 Vector
Returns
Vector with each element multiplied by scalar
Definition at line 364 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator+() [1/3]
CMBVector operator+ (const CMBVector & V1, const CMBVector & V2)
Vector addition operator.
Parameters
V1 First vector
V2 Second vector
Returns
Sum of vectors with labels from V1
Definition at line 314 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator+() [2/3]
CMBVector operator+ (const CMBVector & V1, double d)
Vector-scalar addition operator (vector + scalar)
Parameters
V1 Vector
d Scalar value
Returns
Vector with scalar added to each element
Definition at line 328 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator+() [3/3]
CMBVector operator+ (double d, const CMBVector & V1)
Scalar-vector addition operator (scalar + vector)
Parameters
d Scalar value
V1 Vector
Returns
Vector with scalar added to each element
Definition at line 321 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator-() [1/3]
CMBVector operator- (const CMBVector & V1, const CMBVector & V2)
Vector subtraction operator.
Parameters
V1 First vector
V2 Second vector
Returns
Difference of vectors with labels from V1
Definition at line 335 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator-() [2/3]
CMBVector operator- (const CMBVector & V1, double d)
Vector-scalar subtraction operator (vector - scalar)
Parameters
V1 Vector
d Scalar value
Returns
Vector with scalar subtracted from each element
Definition at line 350 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().
operator-() [3/3]
CMBVector operator- (double d, const CMBVector & V1)
Scalar-vector subtraction operator (scalar - vector)
Parameters
d Scalar value
V1 Vector
Returns
Vector with each element subtracted from scalar
Definition at line 342 of file cmbvector.cpp.
References CMBVector::Labels(), CMBVector::SetLabels(), and CMBVector::size().
operator/()
CMBVector operator/ (const CMBVector & V1, double d)
Vector-scalar division operator.
Parameters
V1 Vector
d Scalar value
Returns
Vector with each element divided by scalar
Definition at line 371 of file cmbvector.cpp.
References CMBVector::Labels(), and CMBVector::SetLabels().