SedSat3: generalchart.h File Reference
generalchart.h File Reference
#include <QDialog>
#include <qchartview.h>
#include <qchart.h>
#include "results.h"
#include "cmbvector.h"
#include "cmbvectorset.h"
#include "cmbvectorsetset.h"
#include <contribution.h>
#include <elemental_profile_set.h>
#include <multiplelinearregressionset.h>
#include <QComboBox>
#include "rangeset.h"
#include <chart.h>
#include <chartview.h>
Classes
class GeneralChart
Namespaces
namespace Ui
Functions
double roundDown (double a, double rounding_number=1.0)
Function Documentation
roundDown()
double roundDown (double a, double rounding_number = 1.0)
Definition at line 130 of file generalchart.cpp.
Referenced by GeneralChart::PlotMatrix(), GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotProfileSet(), and GeneralChart::PlotVector().