SedSat3: generalchart.cpp File Reference
generalchart.cpp File Reference
#include "generalchart.h"
#include "ui_generalchart.h"
#include "resultitem.h"
#include <string>
Functions
double roundDown (double a, double rounding_value)
Function Documentation
roundDown()
double roundDown (double a, double rounding_value)
Definition at line 130 of file generalchart.cpp.
Referenced by GeneralChart::PlotMatrix(), GeneralChart::PlotPredictedConcentration(), GeneralChart::PlotProfileSet(), and GeneralChart::PlotVector().